// Single source of truth for the application menu.
// Both AppSidebar (desktop sidebar) and MainPageMenu (mobile / home grid)
// read from this registry, and the Menu Customization admin page applies
// overrides on top of it. To add a new menu item, add it ONCE here.

import {
  ArrowRightLeft,
  Database,
  FileSpreadsheet,
  Cloud,
  BarChart3,
  Table2,
  LayoutDashboard,
  Settings,
  Users,
  UserCheck,
  TrendingUp,
  Grid3x3,
  CreditCard,
  Link2,
  FileText,
  TicketCheck,
  FileBarChart,
  Key,
  Shield,
  Clock,
  MessageCircle,
  Calendar,
  GraduationCap,
  DollarSign,
  FolderKanban,
  Building2,
  KeyRound,
  Truck,
  Mail,
  HardDrive,
  RotateCcw,
  UserCircle,
  Palmtree,
  ClipboardList,
  Calculator,
  HeartPulse,
  ClipboardCheck,
  FileKey,
  Briefcase,
  Receipt,
  ScrollText,
  Target,
  Undo2,
  Coins,
  ImageIcon,
  Bot,
  Home,
  Headset,
  BookOpen,
  CalendarDays,
  Landmark,
  ListX,
  type LucideIcon,
} from "lucide-react";

export interface DefaultItem {
  url: string;
  defaultEn: string;
  defaultAr: string;
  icon: LucideIcon;
}

export interface DefaultGroup {
  defaultEn: string;
  defaultAr: string;
  items: DefaultItem[];
}

export const DEFAULT_MENU: DefaultGroup[] = [
  {
    defaultEn: "Reports",
    defaultAr: "التقارير",
    items: [
      { url: "/dashboard", defaultEn: "Dashboard", defaultAr: "لوحة التحكم", icon: LayoutDashboard },
      { url: "/ticket-dashboard", defaultEn: "Ticket Dashboard", defaultAr: "لوحة التذاكر", icon: TicketCheck },
      { url: "/shift-dashboard", defaultEn: "Shift Dashboard", defaultAr: "لوحة الورديات", icon: Clock },
      { url: "/task-dashboard", defaultEn: "Task Dashboard", defaultAr: "لوحة المهام", icon: FolderKanban },
      { url: "/user-dashboard", defaultEn: "Employee Dashboard", defaultAr: "لوحة الموظف", icon: Users },
      { url: "/software-licenses", defaultEn: "Software & Subscription", defaultAr: "البرامج والاشتراكات", icon: Key },
      { url: "/reports", defaultEn: "Reports", defaultAr: "التقارير", icon: FileBarChart },
      { url: "/api-documentation", defaultEn: "API Documentation", defaultAr: "توثيق API", icon: FileText },
      { url: "/transactions", defaultEn: "Transactions", defaultAr: "المعاملات", icon: Table2 },
      { url: "/pivot-table", defaultEn: "Pivot Table", defaultAr: "جدول محوري", icon: Grid3x3 },
      { url: "/reports/payment-gateway-consolidation", defaultEn: "Payment Gateway", defaultAr: "توحيد بوابة الدفع", icon: Landmark },
    ],
  },
  {
    defaultEn: "CRM",
    defaultAr: "إدارة العملاء",
    items: [
      { url: "/crm", defaultEn: "Case Board", defaultAr: "خدمة العملاء", icon: Headset },
      { url: "/knowledge-base", defaultEn: "Knowledge Base", defaultAr: "قاعدة المعرفة", icon: BookOpen },
      { url: "/crm-setup", defaultEn: "CRM Setup", defaultAr: "إعداد CRM", icon: Settings },
    ],
  },
  {
    defaultEn: "Entry",
    defaultAr: "الإدخال",
    items: [
      { url: "/load-data", defaultEn: "Load Data", defaultAr: "تحميل البيانات", icon: FileSpreadsheet },
      { url: "/upload-log", defaultEn: "Upload Log", defaultAr: "سجل التحميل", icon: Database },
      { url: "/clear-data", defaultEn: "Clear Data", defaultAr: "مسح البيانات", icon: Database },
      { url: "/tickets", defaultEn: "My Tickets", defaultAr: "تذاكري", icon: FileText },
      { url: "/admin-tickets", defaultEn: "Department Tickets", defaultAr: "تذاكر القسم", icon: Users },
      { url: "/software-license-setup", defaultEn: "License Entry", defaultAr: "إدخال الترخيص", icon: Key },
      { url: "/shift-session", defaultEn: "Shift Session", defaultAr: "جلسة الوردية", icon: Clock },
      { url: "/my-shifts", defaultEn: "My Shifts Calendar", defaultAr: "تقويم وردياتي", icon: Calendar },
      { url: "/shift-follow-up", defaultEn: "Shift Follow-Up", defaultAr: "متابعة الورديات", icon: BarChart3 },
      { url: "/missing-shift-images", defaultEn: "Missing Images", defaultAr: "صور ناقصة", icon: ImageIcon },
      { url: "/shift-attendance-report", defaultEn: "Shift Attendance Report", defaultAr: "سجل حضور الورديات", icon: ClipboardCheck },
      { url: "/tawasoul", defaultEn: "Tawasoul", defaultAr: "تواصل", icon: MessageCircle },
      { url: "/asus-tawasoul", defaultEn: "Asus Tawasoul", defaultAr: "أسس تواصل", icon: Users },
      { url: "/email-manager", defaultEn: "Email Manager", defaultAr: "مدير البريد", icon: Mail },
      { url: "/projects-tasks", defaultEn: "Projects & Tasks", defaultAr: "المشاريع والمهام", icon: FolderKanban },
      { url: "/sales-order-entry", defaultEn: "Sales Order Entry", defaultAr: "إدخال أمر البيع", icon: Receipt },
      { url: "/pricing-scenario", defaultEn: "Pricing Scenario", defaultAr: "سيناريو التسعير", icon: Calculator },
      { url: "/cancelled-orders", defaultEn: "Cancelled Orders Manually Executed", defaultAr: "الطلبات الملغاة تم تنفيذها يدوي", icon: Undo2 },
    ],
  },
  {
    defaultEn: "Setup",
    defaultAr: "الإعداد",
    items: [
      { url: "/reports-setup", defaultEn: "Reports Setup", defaultAr: "إعداد التقارير", icon: Settings },
      { url: "/customer-setup", defaultEn: "Customer Setup", defaultAr: "إعداد العملاء", icon: UserCheck },
      { url: "/customer-profile", defaultEn: "Customer Profile", defaultAr: "ملف العميل", icon: Users },
      { url: "/customer-totals", defaultEn: "Customer Totals", defaultAr: "إجماليات العملاء", icon: TrendingUp },
      { url: "/brand-setup", defaultEn: "Brand Setup", defaultAr: "إعداد العلامات", icon: Settings },
      { url: "/brand-type", defaultEn: "Brand Type", defaultAr: "نوع العلامة", icon: Settings },
      { url: "/product-setup", defaultEn: "Product Setup", defaultAr: "إعداد المنتجات", icon: Database },
      { url: "/payment-method-setup", defaultEn: "Payment Method Setup", defaultAr: "إعداد طرق الدفع", icon: CreditCard },
      { url: "/shift-setup", defaultEn: "Shift Setup", defaultAr: "إعداد الورديات", icon: Clock },
      { url: "/shift-calendar", defaultEn: "Shift Calendar", defaultAr: "تقويم الورديات", icon: BarChart3 },
      { url: "/currency-setup", defaultEn: "Currency Setup", defaultAr: "إعداد العملات", icon: DollarSign },
      { url: "/user-group-setup", defaultEn: "User Groups", defaultAr: "مجموعات المستخدمين", icon: Users },
      { url: "/project-setup", defaultEn: "Project Setup", defaultAr: "إعداد المشاريع", icon: FolderKanban },
      { url: "/task-list", defaultEn: "Task List", defaultAr: "قائمة المهام", icon: ClipboardList },
    ],
  },
  {
    defaultEn: "HR Management",
    defaultAr: "الموارد البشرية",
    items: [
      { url: "/employee-setup", defaultEn: "Employee Setup", defaultAr: "إعداد الموظفين", icon: UserCircle },
      { url: "/employee-self-requests", defaultEn: "Employee Requests", defaultAr: "طلبات الموظفين", icon: ClipboardList },
      { url: "/employee-request-approvals", defaultEn: "Request Approvals", defaultAr: "اعتماد الطلبات", icon: ClipboardCheck },
      { url: "/hr-manager-setup", defaultEn: "HR Manager Setup", defaultAr: "إعداد مديري HR", icon: Users },
      { url: "/vacation-setup", defaultEn: "Vacation Setup", defaultAr: "إعداد الإجازات", icon: Palmtree },
      { url: "/timesheet-management", defaultEn: "Timesheet Management", defaultAr: "إدارة الحضور", icon: ClipboardList },
      { url: "/zk-attendance-logs", defaultEn: "ZK Attendance Logs", defaultAr: "سجلات حضور ZK", icon: Clock },
      { url: "/deduction-rules-setup", defaultEn: "Deduction Rules", defaultAr: "قواعد الخصم", icon: Calculator },
      { url: "/medical-insurance-setup", defaultEn: "Medical Insurance", defaultAr: "التأمين الطبي", icon: HeartPulse },
      { url: "/document-type-setup", defaultEn: "Document Types", defaultAr: "أنواع المستندات", icon: FileText },
      { url: "/attendance-type-setup", defaultEn: "Attendance Types", defaultAr: "أنواع الحضور", icon: Clock },
      { url: "/job-setup", defaultEn: "Job Setup", defaultAr: "إعداد الوظائف", icon: Briefcase },
      { url: "/hr-vacation-calendar", defaultEn: "Vacation Calendar", defaultAr: "تقويم الإجازات", icon: Palmtree },
      { url: "/company-hierarchy", defaultEn: "Company Hierarchy", defaultAr: "الهيكل التنظيمي", icon: Building2 },
      { url: "/company-news", defaultEn: "Company News", defaultAr: "أخبار الشركة", icon: FileText },
      { url: "/department-management", defaultEn: "Department Management", defaultAr: "إدارة الأقسام", icon: Settings },
      { url: "/acknowledgment-documents", defaultEn: "Administrative Decisions", defaultAr: "القرارات الإدارية", icon: ClipboardCheck },
      { url: "/wfh-checkin", defaultEn: "WFH Check-In", defaultAr: "تسجيل حضور من المنزل", icon: Home },
      { url: "/company-wfh-calendar", defaultEn: "WFH Calendar", defaultAr: "تقويم العمل من المنزل", icon: CalendarDays },
    ],
  },
  {
    defaultEn: "Cash Management",
    defaultAr: "إدارة النقدية",
    items: [
      { url: "/bank-setup", defaultEn: "Bank Setup", defaultAr: "إعداد البنوك", icon: Building2 },
      { url: "/treasury-setup", defaultEn: "Treasury Setup", defaultAr: "إعداد الخزائن", icon: DollarSign },
      { url: "/expense-category-setup", defaultEn: "Expense Categories", defaultAr: "فئات المصروفات", icon: Settings },
      { url: "/expense-type-setup", defaultEn: "Expense Types", defaultAr: "أنواع المصروفات", icon: Settings },
      { url: "/cost-center-setup", defaultEn: "Cost Centers", defaultAr: "مراكز التكلفة", icon: Target },
      { url: "/treasury-opening-balance", defaultEn: "Treasury Opening Balance", defaultAr: "رصيد الخزينة الافتتاحي", icon: DollarSign },
      { url: "/treasury-entry", defaultEn: "Treasury Entry", defaultAr: "قيد الخزينة", icon: FileText },
      { url: "/bank-entry", defaultEn: "Bank Entry", defaultAr: "قيد البنك", icon: FileText },
      { url: "/expense-entry", defaultEn: "Expense Entry", defaultAr: "قيد المصروفات", icon: Receipt },
      { url: "/expense-requests", defaultEn: "Expense Requests", defaultAr: "طلبات المصروفات", icon: ClipboardList },
      { url: "/void-payment", defaultEn: "Void Payment", defaultAr: "إلغاء الدفع", icon: Undo2 },
      { url: "/payment-bank-link", defaultEn: "Payment Bank Link", defaultAr: "ربط طرق الدفع بالبنوك", icon: Link2 },
      { url: "/reports/payment-whatif", defaultEn: "Payment What-If", defaultAr: "سيناريو ماذا لو - الدفع", icon: Calculator },
    ],
  },
  {
    defaultEn: "Coins Transaction",
    defaultAr: "معاملات الكوينز",
    items: [
      { url: "/coins-creation", defaultEn: "Coins Purchase Creation", defaultAr: "إنشاء طلب شراء", icon: FileText },
      { url: "/coins-sending", defaultEn: "Sending Transfers", defaultAr: "توجيه التحويلات", icon: Mail },
      { url: "/coins-receiving-phase", defaultEn: "Receiving Phase", defaultAr: "استلام من المورد", icon: ClipboardCheck },
      { url: "/receiving-coins", defaultEn: "Receiving Entry", defaultAr: "إيصال الاستلام", icon: Coins },
      { url: "/coins-workflow-setup", defaultEn: "Workflow Setup", defaultAr: "إعداد سير العمل", icon: Settings },
      { url: "/coins-purchase-followup", defaultEn: "Purchase Follow-Up", defaultAr: "متابعة شراء الكوينز", icon: ClipboardCheck },
      { url: "/supplier-setup", defaultEn: "Supplier Setup", defaultAr: "إعداد الموردين", icon: Truck },
      { url: "/coins-transaction-guide", defaultEn: "User Guide", defaultAr: "دليل المستخدم", icon: FileText },
      { url: "/supplier-advance-payment", defaultEn: "Supplier Advance Payment", defaultAr: "دفعات مقدمة للموردين", icon: DollarSign },
      { url: "/coins-sheets", defaultEn: "Coins Sheets", defaultAr: "شيتات الكوينز", icon: ScrollText },
      { url: "/sales-sheets", defaultEn: "Sales Sheets", defaultAr: "شيت المبيعات", icon: ScrollText },
    ],
  },
  {
    defaultEn: "Admin",
    defaultAr: "الإدارة",
    items: [
      { url: "/user-setup", defaultEn: "User Setup", defaultAr: "إعداد المستخدمين", icon: Users },
      { url: "/user-logins", defaultEn: "Users Logins", defaultAr: "بيانات تسجيل الدخول", icon: KeyRound },
      { url: "/user-emails", defaultEn: "Users & Mails", defaultAr: "المستخدمين والبريد", icon: Mail },
      { url: "/mail-setup", defaultEn: "Mail Setup", defaultAr: "إعداد البريد", icon: Mail },
      { url: "/system-config", defaultEn: "System Configuration", defaultAr: "إعدادات النظام", icon: Shield },
      { url: "/api-integration-status", defaultEn: "API Integration Status", defaultAr: "حالة تكامل API", icon: Cloud },
      { url: "/closing-training", defaultEn: "Closing Training", defaultAr: "تدريب الإغلاق", icon: GraduationCap },
      { url: "/odoo-setup", defaultEn: "Odoo Setup", defaultAr: "إعداد Odoo", icon: Link2 },
      { url: "/excel-sheets", defaultEn: "Excel Setup", defaultAr: "إعداد Excel", icon: FileSpreadsheet },
      { url: "/table-generator", defaultEn: "Table Config", defaultAr: "إعداد الجداول", icon: Database },
      { url: "/pdf-to-excel", defaultEn: "PDF to Excel", defaultAr: "تحويل PDF إلى Excel", icon: FileSpreadsheet },
      { url: "/system-backup", defaultEn: "System Backup", defaultAr: "نسخ احتياطي", icon: HardDrive },
      { url: "/system-restore", defaultEn: "System Restore", defaultAr: "استعادة النظام", icon: RotateCcw },
      { url: "/audit-logs", defaultEn: "Audit Logs", defaultAr: "سجلات التدقيق", icon: ClipboardCheck },
      { url: "/certificate-management", defaultEn: "Certificate Management", defaultAr: "إدارة الشهادات", icon: FileKey },
      { url: "/security-dashboard", defaultEn: "Security Dashboard", defaultAr: "لوحة الأمان", icon: Shield },
      { url: "/api-consumption-logs", defaultEn: "API Consumption Logs", defaultAr: "سجلات استهلاك API", icon: ScrollText },
      { url: "/update-bank-ledger", defaultEn: "Update Bank Ledger", defaultAr: "تحديث سجل البنك", icon: Database },
      { url: "/auto-upload", defaultEn: "Auto Upload", defaultAr: "التحميل التلقائي", icon: Bot },
      { url: "/api-transaction-mapping", defaultEn: "Transaction Mapping", defaultAr: "خريطة حقول المعاملات", icon: ArrowRightLeft },
      { url: "/cancelled-orders-management", defaultEn: "Cancelled Orders Management", defaultAr: "إدارة الطلبات الملغاة", icon: ListX },
      { url: "/menu-customization", defaultEn: "Menu Customization", defaultAr: "تخصيص القائمة", icon: Settings },
    ],
  },
];
