import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    "app.name": "Edara",
    "theme.toggle": "Toggle theme",
    "language.toggle": "Toggle language",
    
    // Sidebar Groups
    "sidebar.reports": "Report & Dashboard",
    "sidebar.entry": "Entry",
    "sidebar.setup": "Setup",
    "sidebar.admin": "Admin",
    
    // Menu Items
    "menu.dashboard": "Dashboard",
    "menu.reports": "Reports",
    "menu.transactions": "Transaction Data",
    "menu.loadData": "Load Data From Excel",
    "menu.clearData": "Clear Data",
    "menu.reportsSetup": "Reports Setup",
    "menu.apiConfig": "API Configuration",
    "menu.excelSetup": "Excel Setup",
    "menu.tableConfig": "Table Configuration",
    "menu.userSetup": "User Setup",
    "menu.customerSetup": "Customer Setup",
    
    // Customer Setup Page
    "customerSetup.title": "Customer Setup",
    "customerSetup.subtitle": "Manage customer information",
    "customerSetup.phone": "Phone",
    "customerSetup.name": "Name",
    "customerSetup.creationDate": "Creation Date",
    "customerSetup.updatedDate": "Updated Date",
    "customerSetup.updatedBy": "Updated By",
    "customerSetup.status": "Status",
    "customerSetup.blocked": "Blocked",
    "customerSetup.blockReason": "Block Reason",
    "customerSetup.actions": "Actions",
    "customerSetup.edit": "Edit",
    "customerSetup.active": "Active",
    "customerSetup.disabled": "Disabled",
    "customerSetup.editCustomer": "Edit Customer",
    "customerSetup.customerName": "Customer Name",
    "customerSetup.customerNamePlaceholder": "Enter customer name",
    "customerSetup.selectStatus": "Select Status",
    "customerSetup.blockReasonPlaceholder": "Enter block reason (if applicable)",
    "customerSetup.cancel": "Cancel",
    "customerSetup.save": "Save Changes",
    "customerSetup.saving": "Saving...",
    "customerSetup.success": "Customer updated successfully",
    "customerSetup.error": "Failed to update customer",
    "customerSetup.loading": "Loading customers...",
    "customerSetup.noData": "No customers found",
    "customerSetup.clearAll": "Clear All Customers",
    "customerSetup.clearConfirm": "Are you sure you want to delete all customers?",
    "customerSetup.cleared": "All customers cleared successfully",
    "customerSetup.filterByName": "Filter by name",
    "customerSetup.filterByPhone": "Filter by phone",
    "customerSetup.filterByBrand": "Filter by brand",
    "customerSetup.filterByProduct": "Filter by product",
    "customerSetup.totalSpend": "Total Spend",
    "customerSetup.viewTransactions": "View Transactions",
    "customerSetup.viewSummary": "View Summary",
    "customerSetup.customerTransactions": "Customer Transactions",
    "customerSetup.customerSummary": "Customer Summary",
    "customerSetup.brand": "Brand",
    "customerSetup.product": "Product",
    "customerSetup.lastTransaction": "Last Transaction",
    "customerSetup.newCustomer": "New Customer",
    "customerSetup.lastTransactionDate": "Last Transaction",
    
    // Brand Setup Page
    "brandSetup.title": "Brand Setup",
    "brandSetup.brandName": "Brand Name",
    "brandSetup.status": "Status",
    "brandSetup.createdDate": "Created Date",
    "brandSetup.updatedDate": "Updated Date",
    "brandSetup.actions": "Actions",
    "brandSetup.addNew": "Add New Brand",
    "brandSetup.editBrand": "Edit Brand",
    "brandSetup.brandNamePlaceholder": "Enter brand name",
    "brandSetup.active": "Active",
    "brandSetup.inactive": "Inactive",
    "brandSetup.cancel": "Cancel",
    "brandSetup.save": "Save",
    "brandSetup.saving": "Saving...",
    "brandSetup.created": "Brand created successfully",
    "brandSetup.updated": "Brand updated successfully",
    "brandSetup.deleted": "Brand deleted successfully",
    "brandSetup.deleteConfirm": "Are you sure you want to delete this brand?",
    "brandSetup.noData": "No brands found",
    
    // Upload Log
    "uploadLog.title": "Upload History",
    "uploadLog.subtitle": "View data upload history and status",
    "uploadLog.date": "Date",
    "uploadLog.fileName": "File Name",
    "uploadLog.uploadedBy": "Uploaded By",
    "uploadLog.status": "Status",
    "uploadLog.recordsProcessed": "Records Processed",
    "uploadLog.newCustomers": "New Customers",
    "uploadLog.excelDates": "Excel Dates",
    "uploadLog.errors": "Errors",
    "uploadLog.completed": "Completed",
    "uploadLog.failed": "Failed",
    "uploadLog.processing": "Processing",
    "uploadLog.view": "View",
    "uploadLog.excelDatesTitle": "Excel File Dates",
    "uploadLog.close": "Close",
    
    // Dashboard - Sales Analytics
    "dashboard.title": "Sales Dashboard",
    "dashboard.subtitle": "Sales Overview",
    "dashboard.totalSales": "Total Sales",
    "dashboard.totalProfit": "Total Profit",
    "dashboard.transactions": "Transactions",
    "dashboard.avgOrderValue": "Avg Order Value",
    "dashboard.salesTrend": "Sales Trend",
    "dashboard.topBrands": "Top Brands by Sales",
    "dashboard.topCategories": "Top 5 Product Categories",
    "dashboard.topProducts": "Top 10 Products",
    "dashboard.paymentMethods": "Payment Methods",
    "dashboard.paymentBrands": "Payment Brands",
    "dashboard.monthComparison": "Monthly Comparison",
    "dashboard.productSummary": "Product Sales Summary",
    "dashboard.incomeStatement": "Income Statement",
    "dashboard.recentTransactions": "Recent Transactions",
    "dashboard.date": "Date",
    "dashboard.customer": "Customer",
    "dashboard.brand": "Brand",
    "dashboard.product": "Product",
    "dashboard.category": "Category",
    "dashboard.amount": "Amount",
    "dashboard.profit": "Profit",
    "dashboard.sales": "Sales",
    "dashboard.viewAll": "View All Transactions",
    "dashboard.loading": "Loading dashboard data...",
    "dashboard.noData": "No sales data available",
    "dashboard.yesterday": "Yesterday",
    "dashboard.thisMonth": "This Month",
    "dashboard.lastMonth": "Last Month",
    "dashboard.dateRange": "Date Range",
    "dashboard.from": "From",
    "dashboard.to": "To",
    "dashboard.apply": "Apply",
    "dashboard.couponSales": "Coupon Sales",
    "dashboard.salesPlusCoupon": "Sales + Coupon",
    "dashboard.costOfSales": "Cost Of Sales",
    "dashboard.ePaymentCharges": "E-Payment Charges",
    "dashboard.netSales": "Net Sales",
    "dashboard.totalSalesWithDiscount": "Total Sales (Including Discounts)",
    "dashboard.discountCoupons": "Discount Coupons",
    "dashboard.shipping": "Shipping",
    "dashboard.taxes": "Taxes",
    "dashboard.customerPurchases": "Customer Purchases Summary",
    "dashboard.customerName": "Customer Name",
    "dashboard.totalValue": "Total Value",
    "dashboard.transactionCount": "Transaction Count",
    "dashboard.filterProduct": "Filter by Product",
    "dashboard.filterCategory": "Filter by Category",
    "dashboard.filterBrand": "Filter by Brand",
    "dashboard.filterCustomer": "Filter by Customer",
    "dashboard.allProducts": "All Products",
    "dashboard.allCategories": "All Categories",
    "dashboard.allBrands": "All Brands",
    "dashboard.allCustomers": "All Customers",
    "dashboard.quantity": "Quantity",
    "dashboard.loadingInitializing": "Initializing...",
    "dashboard.loadingTransactions": "Loading transactions...",
    "dashboard.loadingCalculatingStats": "Calculating statistics...",
    "dashboard.loadingProcessingData": "Processing data...",
    "dashboard.loadingCompleting": "Completing...",
    
    // Transactions Page
    "transactions.title": "All Transactions",
    "transactions.subtitle": "View and manage transaction data",
    "transactions.export": "Export",
    "transactions.search": "Search transactions...",
    "transactions.orderNumber": "Order Number",
    "transactions.userName": "User Name",
    "transactions.paymentMethod": "Payment Method",
    "transactions.paymentType": "Payment Type",
    "transactions.customerPhone": "Customer Phone",
    "transactions.costPrice": "Cost Price",
    "transactions.unitPrice": "Unit Price",
    "transactions.costSold": "Cost Sold",
    "transactions.qty": "Qty",
    "transactions.coinsNumber": "Coins Number",
    
    // Clear Data Page
    "clearData.title": "Clear Data",
    "clearData.subtitle": "Delete data from tables by date range",
    "clearData.selectTable": "Select Table",
    "clearData.selectTablePlaceholder": "Choose a table...",
    "clearData.fromDate": "From Date",
    "clearData.toDate": "To Date",
    "clearData.clearButton": "Clear Data",
    "clearData.confirmTitle": "Confirm Data Deletion",
    "clearData.confirmMessage": "Are you sure you want to delete all records from {table} between {fromDate} and {toDate}? This action cannot be undone.",
    "clearData.cancel": "Cancel",
    "clearData.confirm": "Confirm Delete",
    "clearData.success": "Data cleared successfully",
    "clearData.error": "Error clearing data",
    "clearData.selectTableFirst": "Please select a table first",
    "clearData.selectDates": "Please select both from and to dates",
    
    // Auth Page
    "auth.welcome": "Welcome to Edara",
    "auth.signIn": "Sign in with your credentials",
    "auth.changePassword": "Change your password",
    "auth.setupMFA": "Set up Google Authenticator",
    "auth.verifyMFA": "Enter code from Google Authenticator",
    "auth.email": "Email Address",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.newPassword": "New Password",
    "auth.newPasswordPlaceholder": "Enter new password",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Confirm new password",
    "auth.signInButton": "Sign In",
    "auth.signingIn": "Signing in...",
    "auth.changePasswordButton": "Change Password",
    "auth.updating": "Updating...",
    "auth.resetPassword": "Forgot Password?",
    "auth.resetPasswordSending": "Sending...",
    "auth.scanQR": "Scan this QR code with Google Authenticator",
    "auth.manualEntry": "Manual entry code",
    "auth.enterCode": "Enter 6-digit code",
    "auth.verifying": "Verifying...",
    "auth.verifyButton": "Verify and Continue",
    "auth.cantAccess": "Can't access your app? Reset MFA",
    "auth.backToLogin": "Back to login",
    "auth.passwordResetSent": "Password sent to your email",
    "auth.passwordResetError": "Failed to send password reset email",
    "auth.enterEmailFirst": "Please enter your email first",
    
    // Common
    "common.success": "Success",
    "common.error": "Error",
    "common.loading": "Loading...",
    "common.all": "All",
  },
  ar: {
    // Header
    "app.name": "إدارة",
    "theme.toggle": "تبديل السمة",
    "language.toggle": "تبديل اللغة",
    
    // Sidebar Groups
    "sidebar.reports": "التقارير ولوحة التحكم",
    "sidebar.entry": "الإدخال",
    "sidebar.setup": "الإعداد",
    "sidebar.admin": "الإدارة",
    
    // Menu Items
    "menu.dashboard": "لوحة التحكم",
    "menu.reports": "التقارير",
    "menu.transactions": "بيانات المعاملات",
    "menu.loadData": "تحميل البيانات من Excel",
    "menu.clearData": "حذف البيانات",
    "menu.reportsSetup": "إعداد التقارير",
    "menu.apiConfig": "إعدادات API",
    "menu.excelSetup": "إعدادات Excel",
    "menu.tableConfig": "إعدادات الجداول",
    "menu.userSetup": "إعداد المستخدمين",
    "menu.customerSetup": "إعداد العملاء",
    
    // Customer Setup Page
    "customerSetup.title": "إعداد العملاء",
    "customerSetup.subtitle": "إدارة معلومات العملاء",
    "customerSetup.phone": "الهاتف",
    "customerSetup.name": "الاسم",
    "customerSetup.creationDate": "تاريخ الإنشاء",
    "customerSetup.updatedDate": "تاريخ التحديث",
    "customerSetup.updatedBy": "تم التحديث بواسطة",
    "customerSetup.status": "الحالة",
    "customerSetup.blocked": "محظور",
    "customerSetup.blockReason": "سبب الحظر",
    "customerSetup.actions": "الإجراءات",
    "customerSetup.edit": "تعديل",
    "customerSetup.active": "نشط",
    "customerSetup.disabled": "معطل",
    "customerSetup.editCustomer": "تعديل العميل",
    "customerSetup.customerName": "اسم العميل",
    "customerSetup.customerNamePlaceholder": "أدخل اسم العميل",
    "customerSetup.selectStatus": "اختر الحالة",
    "customerSetup.blockReasonPlaceholder": "أدخل سبب الحظر (إن وجد)",
    "customerSetup.cancel": "إلغاء",
    "customerSetup.save": "حفظ التغييرات",
    "customerSetup.saving": "جاري الحفظ...",
    "customerSetup.success": "تم تحديث العميل بنجاح",
    "customerSetup.error": "فشل تحديث العميل",
    "customerSetup.loading": "جاري تحميل العملاء...",
    "customerSetup.noData": "لا يوجد عملاء",
    "customerSetup.clearAll": "مسح جميع العملاء",
    "customerSetup.clearConfirm": "هل أنت متأكد من حذف جميع العملاء؟",
    "customerSetup.cleared": "تم مسح جميع العملاء بنجاح",
    "customerSetup.filterByName": "تصفية بالاسم",
    "customerSetup.filterByPhone": "تصفية بالهاتف",
    "customerSetup.filterByBrand": "تصفية بالماركة",
    "customerSetup.filterByProduct": "تصفية بالمنتج",
    "customerSetup.totalSpend": "إجمالي الإنفاق",
    "customerSetup.viewTransactions": "عرض المعاملات",
    "customerSetup.viewSummary": "عرض الملخص",
    "customerSetup.customerTransactions": "معاملات العميل",
    "customerSetup.customerSummary": "ملخص العميل",
    "customerSetup.brand": "الماركة",
    "customerSetup.product": "المنتج",
    "customerSetup.lastTransaction": "آخر معاملة",
    "customerSetup.newCustomer": "عميل جديد",
    "customerSetup.lastTransactionDate": "آخر معاملة",
    
    // Brand Setup Page
    "brandSetup.title": "إعداد الماركات",
    "brandSetup.brandName": "اسم الماركة",
    "brandSetup.status": "الحالة",
    "brandSetup.createdDate": "تاريخ الإنشاء",
    "brandSetup.updatedDate": "تاريخ التحديث",
    "brandSetup.actions": "الإجراءات",
    "brandSetup.addNew": "إضافة ماركة جديدة",
    "brandSetup.editBrand": "تعديل الماركة",
    "brandSetup.brandNamePlaceholder": "أدخل اسم الماركة",
    "brandSetup.active": "نشط",
    "brandSetup.inactive": "غير نشط",
    "brandSetup.cancel": "إلغاء",
    "brandSetup.save": "حفظ",
    "brandSetup.saving": "جاري الحفظ...",
    "brandSetup.created": "تم إنشاء الماركة بنجاح",
    "brandSetup.updated": "تم تحديث الماركة بنجاح",
    "brandSetup.deleted": "تم حذف الماركة بنجاح",
    "brandSetup.deleteConfirm": "هل أنت متأكد من حذف هذه الماركة؟",
    "brandSetup.noData": "لا توجد ماركات",
    
    // Upload Log
    "uploadLog.title": "سجل التحميلات",
    "uploadLog.subtitle": "عرض سجل وحالة تحميل البيانات",
    "uploadLog.date": "التاريخ",
    "uploadLog.fileName": "اسم الملف",
    "uploadLog.uploadedBy": "تم التحميل بواسطة",
    "uploadLog.status": "الحالة",
    "uploadLog.recordsProcessed": "السجلات المعالجة",
    "uploadLog.newCustomers": "عملاء جدد",
    "uploadLog.excelDates": "تواريخ Excel",
    "uploadLog.errors": "الأخطاء",
    "uploadLog.completed": "مكتمل",
    "uploadLog.failed": "فشل",
    "uploadLog.processing": "جاري المعالجة",
    "uploadLog.view": "عرض",
    "uploadLog.excelDatesTitle": "تواريخ ملف Excel",
    "uploadLog.close": "إغلاق",
    
    // Dashboard - Sales Analytics
    "dashboard.title": "لوحة المبيعات",
    "dashboard.subtitle": "نظرة عامة على المبيعات",
    "dashboard.totalSales": "إجمالي المبيعات",
    "dashboard.totalProfit": "إجمالي الأرباح",
    "dashboard.transactions": "المعاملات",
    "dashboard.avgOrderValue": "متوسط قيمة الطلب",
    "dashboard.salesTrend": "اتجاه المبيعات",
    "dashboard.topBrands": "أفضل العلامات التجارية",
    "dashboard.topCategories": "أفضل 5 فئات منتجات",
    "dashboard.topProducts": "أفضل 10 منتجات",
    "dashboard.paymentMethods": "طرق الدفع",
    "dashboard.paymentBrands": "علامات الدفع التجارية",
    "dashboard.monthComparison": "مقارنة شهرية",
    "dashboard.productSummary": "ملخص مبيعات المنتجات",
    "dashboard.incomeStatement": "قائمة الدخل",
    "dashboard.recentTransactions": "المعاملات الأخيرة",
    "dashboard.date": "التاريخ",
    "dashboard.customer": "العميل",
    "dashboard.brand": "العلامة التجارية",
    "dashboard.product": "المنتج",
    "dashboard.category": "الفئة",
    "dashboard.amount": "المبلغ",
    "dashboard.profit": "الربح",
    "dashboard.sales": "المبيعات",
    "dashboard.viewAll": "عرض جميع المعاملات",
    "dashboard.loading": "جاري تحميل بيانات لوحة التحكم...",
    "dashboard.noData": "لا توجد بيانات مبيعات متاحة",
    "dashboard.yesterday": "أمس",
    "dashboard.thisMonth": "هذا الشهر",
    "dashboard.lastMonth": "الشهر الماضي",
    "dashboard.dateRange": "نطاق التاريخ",
    "dashboard.from": "من",
    "dashboard.to": "إلى",
    "dashboard.apply": "تطبيق",
    "dashboard.couponSales": "مبيعات الكوبونات",
    "dashboard.salesPlusCoupon": "المبيعات + الكوبونات",
    "dashboard.costOfSales": "تكلفة المبيعات",
    "dashboard.ePaymentCharges": "رسوم الدفع الإلكتروني",
    "dashboard.netSales": "صافي المبيعات",
    "dashboard.totalSalesWithDiscount": "إجمالي المبيعات (تشمل التخفيضات)",
    "dashboard.discountCoupons": "كوبونات التخفيض",
    "dashboard.shipping": "الشحن",
    "dashboard.taxes": "الضرائب",
    "dashboard.customerPurchases": "ملخص مشتريات العملاء",
    "dashboard.customerName": "اسم العميل",
    "dashboard.totalValue": "القيمة الإجمالية",
    "dashboard.transactionCount": "عدد المعاملات",
    "dashboard.filterProduct": "تصفية حسب المنتج",
    "dashboard.filterCategory": "تصفية حسب الفئة",
    "dashboard.filterBrand": "تصفية حسب العلامة التجارية",
    "dashboard.filterCustomer": "تصفية حسب العميل",
    "dashboard.allProducts": "جميع المنتجات",
    "dashboard.allCategories": "جميع الفئات",
    "dashboard.allBrands": "جميع العلامات التجارية",
    "dashboard.allCustomers": "جميع العملاء",
    "dashboard.quantity": "الكمية",
    "dashboard.loadingInitializing": "جاري التهيئة...",
    "dashboard.loadingTransactions": "جاري تحميل المعاملات...",
    "dashboard.loadingCalculatingStats": "جاري حساب الإحصائيات...",
    "dashboard.loadingProcessingData": "جاري معالجة البيانات...",
    "dashboard.loadingCompleting": "جاري الإنهاء...",
    
    // Transactions Page
    "transactions.title": "جميع المعاملات",
    "transactions.subtitle": "عرض وإدارة بيانات المعاملات",
    "transactions.export": "تصدير",
    "transactions.search": "البحث في المعاملات...",
    "transactions.orderNumber": "رقم الطلب",
    "transactions.userName": "اسم المستخدم",
    "transactions.paymentMethod": "طريقة الدفع",
    "transactions.paymentType": "نوع الدفع",
    "transactions.customerPhone": "هاتف العميل",
    "transactions.costPrice": "سعر التكلفة",
    "transactions.unitPrice": "سعر الوحدة",
    "transactions.costSold": "التكلفة المباعة",
    "transactions.qty": "الكمية",
    "transactions.coinsNumber": "رقم العملات",
    
    // Clear Data Page
    "clearData.title": "حذف البيانات",
    "clearData.subtitle": "حذف البيانات من الجداول حسب نطاق التاريخ",
    "clearData.selectTable": "اختر الجدول",
    "clearData.selectTablePlaceholder": "اختر جدولاً...",
    "clearData.fromDate": "من تاريخ",
    "clearData.toDate": "إلى تاريخ",
    "clearData.clearButton": "حذف البيانات",
    "clearData.confirmTitle": "تأكيد حذف البيانات",
    "clearData.confirmMessage": "هل أنت متأكد من حذف جميع السجلات من {table} بين {fromDate} و {toDate}؟ لا يمكن التراجع عن هذا الإجراء.",
    "clearData.cancel": "إلغاء",
    "clearData.confirm": "تأكيد الحذف",
    "clearData.success": "تم حذف البيانات بنجاح",
    "clearData.error": "خطأ في حذف البيانات",
    "clearData.selectTableFirst": "الرجاء اختيار جدول أولاً",
    "clearData.selectDates": "الرجاء اختيار كلا التاريخين (من وإلى)",
    
    // Auth Page
    "auth.welcome": "مرحباً بك في إدارة",
    "auth.signIn": "تسجيل الدخول بيانات الاعتماد الخاصة بك",
    "auth.changePassword": "تغيير كلمة المرور",
    "auth.setupMFA": "إعداد المصادقة الثنائية",
    "auth.verifyMFA": "أدخل الرمز من تطبيق المصادقة",
    "auth.email": "البريد الإلكتروني",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "كلمة المرور",
    "auth.passwordPlaceholder": "أدخل كلمة المرور",
    "auth.newPassword": "كلمة المرور الجديدة",
    "auth.newPasswordPlaceholder": "أدخل كلمة المرور الجديدة",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.confirmPasswordPlaceholder": "أكد كلمة المرور الجديدة",
    "auth.signInButton": "تسجيل الدخول",
    "auth.signingIn": "جاري تسجيل الدخول...",
    "auth.changePasswordButton": "تغيير كلمة المرور",
    "auth.updating": "جاري التحديث...",
    "auth.resetPassword": "نسيت كلمة المرور؟",
    "auth.resetPasswordSending": "جاري الإرسال...",
    "auth.scanQR": "امسح رمز QR باستخدام تطبيق المصادقة",
    "auth.manualEntry": "رمز الإدخال اليدوي",
    "auth.enterCode": "أدخل الرمز المكون من 6 أرقام",
    "auth.verifying": "جاري التحقق...",
    "auth.verifyButton": "تحقق ومتابعة",
    "auth.cantAccess": "لا يمكنك الوصول إلى تطبيقك؟ إعادة تعيين المصادقة الثنائية",
    "auth.backToLogin": "العودة لتسجيل الدخول",
    "auth.passwordResetSent": "تم إرسال كلمة المرور إلى بريدك الإلكتروني",
    "auth.passwordResetError": "فشل إرسال بريد إعادة تعيين كلمة المرور",
    "auth.enterEmailFirst": "الرجاء إدخال بريدك الإلكتروني أولاً",
    
    // Common
    "common.success": "نجح",
    "common.error": "خطأ",
    "common.loading": "جاري التحميل...",
    "common.all": "الكل",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ar");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language || "ar";
    setLanguage(savedLanguage);
    document.documentElement.setAttribute("lang", savedLanguage);
    document.documentElement.setAttribute("dir", savedLanguage === "ar" ? "rtl" : "ltr");
  }, []);

  const toggleLanguage = () => {
    const newLanguage: Language = language === "en" ? "ar" : "en";
    setLanguage(newLanguage);
    localStorage.setItem("language", newLanguage);
    document.documentElement.setAttribute("lang", newLanguage);
    document.documentElement.setAttribute("dir", newLanguage === "ar" ? "rtl" : "ltr");
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}