import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "en" | "ar";

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Header
    "app.name": "Edara",
    "theme.toggle": "Toggle theme",
    "language.toggle": "Toggle language",
    
    // Sidebar Groups
    "sidebar.reports": "Report & Dashboard",
    "sidebar.entry": "Entry",
    "sidebar.setup": "Setup",
    "sidebar.admin": "Admin",
    
    // Menu Items
    "menu.dashboard": "Dashboard",
    "menu.reports": "Reports",
    
    // Reports Page
    "reports.title": "Reports",
    "reports.subtitle": "Select a report to view parameters and run",
    "reports.revenueByBrandType.name": "Revenue by Brand Type",
    "reports.revenueByBrandType.description": "Calculate total revenue based on brand type",
    "reports.costByBrandType.name": "Cost by Brand Type",
    "reports.costByBrandType.description": "Calculate total cost based on brand type",
    "reports.viewReport": "View Report",
    
    // Revenue by Brand Type Report
    "revenueReport.title": "Revenue by Brand Type Report",
    "revenueReport.parameters": "Report Parameters",
    "revenueReport.dateFrom": "Date From",
    "revenueReport.dateTo": "Date To",
    "revenueReport.brandType": "Brand Type",
    "revenueReport.allBrandTypes": "All Brand Types",
    "revenueReport.selectBrandType": "Select brand type",
    "revenueReport.runReport": "Run Report",
    "revenueReport.exportCSV": "Export CSV",
    "revenueReport.print": "Print",
    "revenueReport.reportDetails": "Report Details",
    "revenueReport.generatedOn": "Generated On",
    "revenueReport.selectionCriteria": "Selection Criteria",
    "revenueReport.dateRange": "Date Range",
    "revenueReport.to": "to",
    "revenueReport.reportData": "Report Data",
    "revenueReport.brandTypeName": "Brand Type Name",
    "revenueReport.totalRevenue": "Total Revenue",
    "revenueReport.transactionCount": "Transaction Count",
    "revenueReport.total": "Total",
    "revenueReport.average": "Average",
    "revenueReport.noData": "No data available for the selected criteria",
    
    // Cost by Brand Type Report
    "costReport.title": "Cost by Brand Type Report",
    "costReport.parameters": "Report Parameters",
    "costReport.dateFrom": "Date From",
    "costReport.dateTo": "Date To",
    "costReport.brandType": "Brand Type",
    "costReport.allBrandTypes": "All Brand Types",
    "costReport.selectBrandType": "Select brand type",
    "costReport.runReport": "Run Report",
    "costReport.exportCSV": "Export CSV",
    "costReport.print": "Print",
    "costReport.reportDetails": "Report Details",
    "costReport.generatedOn": "Generated On",
    "costReport.selectionCriteria": "Selection Criteria",
    "costReport.dateRange": "Date Range",
    "costReport.to": "to",
    "costReport.reportData": "Report Data",
    "costReport.brandTypeName": "Brand Type Name",
    "costReport.totalCost": "Total Cost",
    "costReport.transactionCount": "Transaction Count",
    "costReport.total": "Total",
    "costReport.average": "Average",
    "costReport.noData": "No data available for the selected criteria",
    "menu.transactions": "Transaction Data",
    "menu.pivotTable": "Pivot Table",
    "menu.loadData": "Load Data From Excel",
    "menu.clearData": "Clear Data",
    "menu.reportsSetup": "Reports Setup",
    "menu.apiConfig": "API Configuration",
    "menu.excelSetup": "Excel Setup",
    "menu.tableConfig": "Table Configuration",
    "menu.userSetup": "User Setup",
    "menu.customerSetup": "Customer Setup",
    "menu.customerProfile": "Customer Profile",
    "menu.customerTotals": "Customer Totals",
    "menu.brandSetup": "Brand Setup",
    "menu.brandType": "Brand Type",
    "menu.productSetup": "Product Setup",
    
    // Ticket Details Page
    "ticketDetails.backToTickets": "Back to Tickets",
    "ticketDetails.loading": "Loading ticket details...",
    "ticketDetails.notFound": "Ticket not found",
    "ticketDetails.ticketNumber": "Ticket #",
    "ticketDetails.department": "Department:",
    "ticketDetails.created": "Created:",
    "ticketDetails.createdBy": "Created by:",
    "ticketDetails.email": "Email:",
    "ticketDetails.description": "Description",
    "ticketDetails.commentsUpdates": "Comments & Updates",
    "ticketDetails.noComments": "No comments yet",
    "ticketDetails.addCommentPlaceholder": "Add a comment...",
    "ticketDetails.addComment": "Add Comment",
    "ticketDetails.internalNote": "Internal Note",
    "ticketDetails.success": "Success",
    "ticketDetails.commentAdded": "Comment added successfully",
    "ticketDetails.error": "Error",
    
    // Customer Setup Page
    "customerSetup.title": "Customer Setup",
    "customerSetup.subtitle": "Manage customer information",
    "customerSetup.phone": "Phone",
    "customerSetup.name": "Name",
    "customerSetup.creationDate": "Creation Date",
    "customerSetup.updatedDate": "Updated Date",
    "customerSetup.updatedBy": "Updated By",
    "customerSetup.status": "Status",
    "customerSetup.blocked": "Blocked",
    "customerSetup.blockReason": "Block Reason",
    "customerSetup.actions": "Actions",
    "customerSetup.edit": "Edit",
    "customerSetup.active": "Active",
    "customerSetup.disabled": "Disabled",
    "customerSetup.editCustomer": "Edit Customer",
    "customerSetup.customerName": "Customer Name",
    "customerSetup.customerNamePlaceholder": "Enter customer name",
    "customerSetup.selectStatus": "Select Status",
    "customerSetup.blockReasonPlaceholder": "Enter block reason (if applicable)",
    "customerSetup.cancel": "Cancel",
    "customerSetup.save": "Save Changes",
    "customerSetup.saving": "Saving...",
    "customerSetup.success": "Customer updated successfully",
    "customerSetup.error": "Failed to update customer",
    "customerSetup.loading": "Loading customers...",
    "customerSetup.noData": "No customers found",
    "customerSetup.clearAll": "Clear All Customers",
    "customerSetup.clearConfirm": "Are you sure you want to delete all customers?",
    "customerSetup.cleared": "All customers cleared successfully",
    "customerSetup.filterByName": "Filter by name",
    "customerSetup.filterByPhone": "Filter by phone",
    "customerSetup.filterByBrand": "Filter by brand",
    "customerSetup.filterByProduct": "Filter by product",
    "customerSetup.totalSpend": "Total Spend",
    "customerSetup.viewTransactions": "View Transactions",
    "customerSetup.viewSummary": "View Summary",
    "customerSetup.customerTransactions": "Customer Transactions",
    "customerSetup.customerSummary": "Customer Summary",
    "customerSetup.brand": "Brand",
    "customerSetup.product": "Product",
    "customerSetup.lastTransaction": "Last Transaction",
    "customerSetup.newCustomer": "New Customer",
    "customerSetup.lastTransactionDate": "Last Transaction",
    "customerSetup.customers": "Customers",
    "customerSetup.orderNumber": "Order Number",
    "customerSetup.syncCustomers": "Sync Customers",
    "customerSetup.missingCustomersFound": "Missing customers found",
    "customerSetup.noMissingCustomers": "No missing customers found",
    "customerSetup.customersAdded": "customers added successfully",
    "customerSetup.date": "Date",
    "customerSetup.quantity": "Quantity",
    "customerSetup.paymentMethod": "Payment Method",
    "customerSetup.paymentType": "Payment Type",
    "customerSetup.total": "Total",
    "customerSetup.noTransactions": "No transactions found",
    "customerSetup.totalTransactionsCount": "Total Transactions",
    "customerSetup.totalAmount": "Total Amount",
    "customerSetup.partnerId": "Partner ID",
    "customerSetup.notSynced": "Not Synced",
    "customerSetup.addNew": "Add New Customer",
    "customerSetup.phonePlaceholder": "Enter phone number",
    "customerSetup.namePlaceholder": "Enter customer name",
    "customerSetup.created": "Customer created successfully",
    "customerSetup.updated": "Customer updated successfully",
    "customerSetup.deleted": "Customer deleted successfully",
    "customerSetup.deleteConfirm": "Are you sure you want to delete this customer?",
    "customerSetup.fillAllFields": "Please fill all required fields",
    "customerSetup.delete": "Delete",
    "customerSetup.customerUpdated": "Customer updated successfully",
    
    // Brand Setup Page
    "brandSetup.title": "Brand Setup",
    "brandSetup.brandName": "Brand Name",
    "brandSetup.status": "Status",
    "brandSetup.createdDate": "Created Date",
    "brandSetup.updatedDate": "Updated Date",
    "brandSetup.actions": "Actions",
    "brandSetup.addNew": "Add New Brand",
    "brandSetup.editBrand": "Edit Brand",
    "brandSetup.brandNamePlaceholder": "Enter brand name",
    "brandSetup.active": "Active",
    "brandSetup.inactive": "Inactive",
    "brandSetup.cancel": "Cancel",
    "brandSetup.save": "Save",
    "brandSetup.saving": "Saving...",
    "brandSetup.created": "Brand created successfully",
    "brandSetup.updated": "Brand updated successfully",
    "brandSetup.deleted": "Brand deleted successfully",
    "brandSetup.deleteConfirm": "Are you sure you want to delete this brand?",
    "brandSetup.noData": "No brands found",
    "brandSetup.brandType": "Brand Type",
    "brandSetup.selectBrandType": "Select Brand Type",
    "brandSetup.noBrandType": "No Brand Type",
    
    // Brand Type Page
    "brandType.title": "Brand Type",
    "brandType.brandCode": "Brand Code",
    "brandType.brandName": "Brand Name",
    "brandType.status": "Status",
    "brandType.createdDate": "Created Date",
    "brandType.updatedDate": "Updated Date",
    "brandType.actions": "Actions",
    "brandType.addNew": "Add New Brand Type",
    "brandType.editBrand": "Edit Brand Type",
    "brandType.brandCodePlaceholder": "Enter brand code",
    "brandType.brandNamePlaceholder": "Enter brand name",
    "brandType.active": "Active",
    "brandType.inactive": "Inactive",
    "brandType.cancel": "Cancel",
    "brandType.save": "Save",
    "brandType.saving": "Saving...",
    "brandType.created": "Brand type created successfully",
    "brandType.updated": "Brand type updated successfully",
    "brandType.deleted": "Brand type deleted successfully",
    "brandType.deleteConfirm": "Are you sure you want to delete this brand type?",
    "brandType.noData": "No brand types found",
    "brandType.filterByCode": "Filter by Brand Code",
    "brandType.filterByName": "Filter by Brand Name",
    "brandType.filterByCodePlaceholder": "Search brand code...",
    "brandType.filterByNamePlaceholder": "Search brand name...",
    "brandType.noMatches": "No brand types match your filters",
    
    // Product Setup Page
    "productSetup.title": "Product Setup",
    "productSetup.productId": "Product ID",
    "productSetup.productName": "Product Name",
    "productSetup.productPrice": "Product Price",
    "productSetup.productCost": "Product Cost",
    "productSetup.brand": "Brand",
    "productSetup.brandPlaceholder": "Enter brand name",
    "productSetup.status": "Status",
    "productSetup.createdDate": "Created Date",
    "productSetup.actions": "Actions",
    "productSetup.addNew": "Add New Product",
    "productSetup.editProduct": "Edit Product",
    "productSetup.productIdPlaceholder": "Enter product ID (optional)",
    "productSetup.productNamePlaceholder": "Enter product name",
    "productSetup.productPricePlaceholder": "Enter product price",
    "productSetup.productCostPlaceholder": "Enter product cost",
    "productSetup.active": "Active",
    "productSetup.inactive": "Inactive",
    "productSetup.cancel": "Cancel",
    "productSetup.save": "Save",
    "productSetup.created": "Product created successfully",
    "productSetup.updated": "Product updated successfully",
    "productSetup.deleted": "Product deleted successfully",
    "productSetup.deleteConfirm": "Are you sure you want to delete this product?",
    "productSetup.filterByName": "Filter by product name",
    "productSetup.filterByBrand": "Filter by brand",
    "productSetup.noData": "No products found",
    "productSetup.viewGrid": "Grid",
    "productSetup.viewTree": "Tree",
    "productSetup.noBrand": "No Brand",
    "productSetup.product": "product",
    "productSetup.products": "products",
    "productSetup.moreDetails": "More Details",
    "productSetup.stock": "Stock",
    "productSetup.pricing": "Pricing",
    "productSetup.freeCoins": "Free Coins",
    "productSetup.options": "Options",
    "productSetup.customerGroupPrices": "Customer Group Prices",
    "productSetup.discounts": "Discounts",
    "productSetup.seo": "SEO",
    "productSetup.quantity": "Quantity",
    "productSetup.quantityPlaceholder": "Enter quantity",
    "productSetup.sku": "SKU",
    "productSetup.skuPlaceholder": "Enter SKU",
    "productSetup.location": "Location",
    "productSetup.locationPlaceholder": "Enter location",
    "productSetup.model": "Model",
    "productSetup.modelPlaceholder": "Enter model",
    "productSetup.minQuantity": "Minimum Quantity",
    "productSetup.minQuantityPlaceholder": "Enter minimum quantity",
    "productSetup.stockStatus": "Stock Status",
    "productSetup.inStock": "In Stock",
    "productSetup.outOfStock": "Out of Stock",
    "productSetup.preOrder": "Pre-Order",
    "productSetup.specialPrice": "Special Price",
    "productSetup.specialPricePlaceholder": "Enter special price",
    "productSetup.specialStartDate": "Special Start Date",
    "productSetup.specialEndDate": "Special End Date",
    "productSetup.taxClass": "Tax Class",
    "productSetup.taxClassPlaceholder": "Enter tax class",
    "productSetup.defaultTax": "Default Tax",
    "productSetup.noTax": "No Tax",
    "productSetup.coinsGiven": "Coins Given",
    "productSetup.coinsGivenPlaceholder": "Enter coins given",
    "productSetup.coinsRedeemed": "Coins Redeemed",
    "productSetup.coinsRedeemedPlaceholder": "Enter coins redeemed",
    "productSetup.optionName": "Option Name",
    "productSetup.optionNamePlaceholder": "Enter option name",
    "productSetup.optionValue": "Option Value",
    "productSetup.optionValuePlaceholder": "Enter option value",
    "productSetup.required": "Required",
    "productSetup.addOption": "Add Option",
    "productSetup.customerGroup": "Customer Group",
    "productSetup.customerGroupPlaceholder": "Enter customer group",
    "productSetup.groupPrice": "Group Price",
    "productSetup.groupPricePlaceholder": "Enter group price",
    "productSetup.addGroupPrice": "Add Group Price",
    "productSetup.discountGroup": "Discount Group",
    "productSetup.discountGroupPlaceholder": "Enter discount group",
    "productSetup.discountQuantity": "Discount Quantity",
    "productSetup.discountQuantityPlaceholder": "Enter discount quantity",
    "productSetup.discountPriority": "Discount Priority",
    "productSetup.discountPriorityPlaceholder": "Enter discount priority",
    "productSetup.discountPrice": "Discount Price",
    "productSetup.discountPricePlaceholder": "Enter discount price",
    "productSetup.discountStartDate": "Discount Start Date",
    "productSetup.discountEndDate": "Discount End Date",
    "productSetup.addDiscount": "Add Discount",
    "productSetup.metaTitle": "Meta Title",
    "productSetup.metaTitlePlaceholder": "Enter meta title",
    "productSetup.metaDescription": "Meta Description",
    "productSetup.metaDescriptionPlaceholder": "Enter meta description",
    "productSetup.metaKeywords": "Meta Keywords",
    "productSetup.metaKeywordsPlaceholder": "Enter meta keywords",
    "productSetup.mobile": "Mobile",
    "productSetup.enabled": "Enabled",
    "productSetup.disabled": "Disabled",
    "productSetup.on": "ON",
    "productSetup.off": "OFF",
    "productSetup.notifyQty": "Reorder Point",
    "productSetup.notifyQtyPlaceholder": "Enter reorder point quantity",
    "productSetup.maxQuantity": "Max order qty",
    "productSetup.maxQuantityPlaceholder": "Enter maximum quantity",
    "productSetup.minCoins": "Min coins",
    "productSetup.minCoinsPlaceholder": "Enter minimum coins",
    "productSetup.maxCoins": "Max coins",
    "productSetup.maxCoinsPlaceholder": "Enter maximum coins",
    "productSetup.productInformation": "Product Information",
    "productSetup.stockManagement": "Stock Management",
    "productSetup.barcode": "Barcode",
    "productSetup.category": "Category",
    "productSetup.weight": "Weight",
    "productSetup.supplier": "Supplier",
    "productSetup.description": "Description",
    "productSetup.notes": "Notes",
    "productSetup.stockQuantity": "Stock Quantity",
    "productSetup.reorderPoint": "Reorder Point",
    "productSetup.taxIncluded": "Tax Included",
    "productSetup.taxExcluded": "Tax Excluded",
    "productSetup.min": "Min",
    "productSetup.max": "Max",
    "productSetup.salePoints": "Sale Points",
    "productSetup.purchasePoints": "Purchase Points",
    "productSetup.allGroups": "All Groups",
    "productSetup.vip": "VIP",
    "productSetup.store": "Store",
    "productSetup.purpleStore": "Purple Store",
    "productSetup.allCustomerGroups": "All Customers Groups",
    "productSetup.fixed": "Fixed",
    "productSetup.percentage": "%",
    "productSetup.coinsNumber": "Coins Number",
    "productSetup.coinsPrice": "Coins Price",
    "productSetup.optionId": "Option ID",
    "productSetup.groupName": "Group Name",
    "productSetup.price": "Price",
    "productSetup.discountType": "Discount Type",
    "productSetup.salePrice": "Sale Price",
    "productSetup.purchasePrice": "Purchase Price",
    "productSetup.amountType": "Amount Type",
    "productSetup.amount": "Amount",
    "productSetup.startDate": "Start Date",
    "productSetup.endDate": "End Date",
    "productSetup.arabic": "Arabic",
    "productSetup.english": "English",
    "productSetup.leadtime": "Lead Time (Days)",
    "productSetup.safetyStock": "Safety Stock",
    "productSetup.abcAnalysis": "ABC Analysis",
    
    // Upload Log
    "uploadLog.title": "Upload History",
    "uploadLog.subtitle": "View data upload history and status",
    "uploadLog.date": "Date",
    "uploadLog.fileName": "File Name",
    "uploadLog.uploadedBy": "Uploaded By",
    "uploadLog.status": "Status",
    "uploadLog.recordsProcessed": "Records Processed",
    "uploadLog.newCustomers": "New Customers",
    "uploadLog.excelDates": "Excel Dates",
    "uploadLog.errors": "Errors",
    "uploadLog.excelDatesTitle": "Excel Dates in File",
    "uploadLog.view": "View",
    "uploadLog.summary": "Summary",
    "uploadLog.viewSummary": "View Summary",
    "uploadLog.uploadSummary": "Upload Summary",
    "uploadLog.summaryDescription": "Summary of the upload operation",
    "uploadLog.totalValue": "Total Value",
    "uploadLog.newProducts": "New Products",
    "uploadLog.dateRange": "Date Range",
    "uploadLog.completed": "Completed",
    "uploadLog.failed": "Failed",
    "uploadLog.processing": "Processing",
    "uploadLog.close": "Close",
    "uploadLog.updateBankFees": "Update Bank Fees",
    "uploadLog.updatingBankFees": "Updating bank fees...",
    "uploadLog.bankFeesUpdated": "Bank fees updated successfully",
    "uploadLog.bankFeesUpdateError": "Error updating bank fees",
    
    // Dashboard - Sales Analytics
    "dashboard.title": "Sales Dashboard",
    "dashboard.subtitle": "Sales Overview",
    "dashboard.totalSales": "Total Sales",
    "dashboard.totalProfit": "Total Profit",
    "dashboard.transactions": "Transactions",
    "dashboard.avgOrderValue": "Avg Order Value",
    "dashboard.salesTrend": "Sales Trend",
    "dashboard.topBrands": "Top Brands by Sales",
    "dashboard.topCategories": "Top 5 Product Categories",
    "dashboard.topProducts": "Top 10 Products",
    "dashboard.paymentMethods": "Payment Methods",
    "dashboard.paymentBrands": "Payment Brands",
    "dashboard.monthComparison": "Monthly Comparison",
    "dashboard.productSummary": "Product Sales Summary",
    "dashboard.incomeStatement": "Income Statement",
    "dashboard.recentTransactions": "Recent Transactions",
    "dashboard.date": "Date",
    "dashboard.customer": "Customer",
    "dashboard.brand": "Brand",
    "dashboard.product": "Product",
    "dashboard.category": "Category",
    "dashboard.amount": "Amount",
    "dashboard.profit": "Profit",
    "dashboard.sales": "Sales",
    "dashboard.viewAll": "View All Transactions",
    "dashboard.loading": "Loading dashboard data...",
    "dashboard.noData": "No sales data available",
    "dashboard.yesterday": "Yesterday",
    "dashboard.thisMonth": "This Month",
    "dashboard.lastMonth": "Last Month",
    "dashboard.dateRange": "Date Range",
    "dashboard.from": "From",
    "dashboard.to": "To",
    "dashboard.apply": "Apply",
    "dashboard.couponSales": "Coupon Sales",
    "dashboard.salesPlusCoupon": "Sales + Coupon",
    "dashboard.costOfSales": "Cost Of Sales",
    "dashboard.ePaymentCharges": "E-Payment Charges",
    "dashboard.netSales": "Net Sales",
    "dashboard.totalSalesWithDiscount": "Total Sales (Including Discounts)",
    "dashboard.discountCoupons": "Discount Coupons",
    "dashboard.shipping": "Shipping",
    "dashboard.taxes": "Taxes",
    "dashboard.totalPoints": "Total Points",
    "dashboard.pointsCost": "Points Cost",
    "dashboard.pointTransactions": "Point Transactions",
    "dashboard.pointTransactionsEmpty": "No point transactions found",
    "dashboard.customerPurchases": "Customer Purchases Summary",
    "dashboard.customerName": "Customer Name",
    "dashboard.totalValue": "Total Value",
    "dashboard.transactionCount": "Transaction Count",
    "dashboard.filterProduct": "Filter by Product",
    "dashboard.filterCategory": "Filter by Category",
    "dashboard.filterBrand": "Filter by Brand",
    "dashboard.filterCustomer": "Filter by Customer",
    "dashboard.allProducts": "All Products",
    "dashboard.allCategories": "All Categories",
    "dashboard.allBrands": "All Brands",
    "dashboard.allCustomers": "All Customers",
    "dashboard.quantity": "Quantity",
    "dashboard.loadingInitializing": "Initializing...",
    "dashboard.loadingTransactions": "Loading transactions...",
    "dashboard.loadingCalculatingStats": "Calculating statistics...",
    "dashboard.loadingProcessingData": "Processing data...",
    "dashboard.loadingCompleting": "Completing...",
    "dashboard.crmReminder": "CRM Reminder",
    "dashboard.notes": "Notes",
    "dashboard.nextAction": "Next Action",
    "dashboard.reminderDate": "Reminder Date",
    "dashboard.noReminders": "No reminders at this time",
    "dashboard.orderNumber": "Order Number",
    "dashboard.paymentMethod": "Payment Method",
    "dashboard.status": "Status",
    "dashboard.total": "Total",
    "dashboard.coinsByBrand": "Total Coins by Brand",
    "dashboard.brandName": "Brand Name",
    "dashboard.totalCoins": "Total Coins",
    "dashboard.noCoinsData": "No coins data available",
    
    // Transactions Page
    "transactions.title": "All Transactions",
    "transactions.subtitle": "View and manage transaction data",
    "transactions.export": "Export",
    "transactions.search": "Search transactions...",
    "transactions.searchCustomerProduct": "Search customer or product...",
    "transactions.filterByPhone": "Filter by phone number...",
    "transactions.filterByOrderNumber": "Filter by order number...",
    "transactions.orderNumber": "Order Number",
    "transactions.userName": "User Name",
    "transactions.paymentMethod": "Payment Method",
    "transactions.paymentType": "Payment Type",
    "transactions.customerPhone": "Customer Phone",
    "transactions.costPrice": "Cost Price",
    "transactions.unitPrice": "Unit Price",
    "transactions.costSold": "Cost Sold",
    "transactions.qty": "Qty",
    "transactions.coinsNumber": "Coins Number",
    "transactions.vendorName": "Vendor Name",
    "transactions.orderStatus": "Order Status",
    
    // Clear Data Page
    "clearData.title": "Clear Data",
    "clearData.subtitle": "Delete data from tables by date range",
    "clearData.selectTable": "Select Table",
    "clearData.selectTablePlaceholder": "Choose a table...",
    "clearData.fromDate": "From Date",
    "clearData.toDate": "To Date",
    "clearData.clearButton": "Clear Data",
    "clearData.confirmTitle": "Confirm Data Deletion",
    "clearData.confirmMessage": "Are you sure you want to delete all records from {table} between {fromDate} and {toDate}? This action cannot be undone.",
    "clearData.cancel": "Cancel",
    "clearData.confirm": "Confirm Delete",
    "clearData.success": "Data cleared successfully",
    "clearData.error": "Error clearing data",
    "clearData.selectTableFirst": "Please select a table first",
    "clearData.selectDates": "Please select both from and to dates",
    
    // Welcome/Landing Page
    "welcome.title": "Welcome to Edara",
    "welcome.subtitle": "Your business management system",
    
    // Auth Page
    "auth.welcome": "Welcome to Edara",
    "auth.signIn": "Sign in with your credentials",
    "auth.changePassword": "Change your password",
    "auth.setupMFA": "Set up Google Authenticator",
    "auth.verifyMFA": "Enter code from Google Authenticator",
    "auth.email": "Email Address",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "Password",
    "auth.passwordPlaceholder": "Enter your password",
    "auth.newPassword": "New Password",
    "auth.newPasswordPlaceholder": "Enter new password",
    "auth.confirmPassword": "Confirm Password",
    "auth.confirmPasswordPlaceholder": "Confirm new password",
    "auth.signInButton": "Sign In",
    "auth.signingIn": "Signing in...",
    "auth.changePasswordButton": "Change Password",
    "auth.updating": "Updating...",
    "auth.resetPassword": "Forgot Password?",
    "auth.resetPasswordSending": "Sending...",
    "auth.scanQR": "Scan this QR code with Google Authenticator",
    "auth.manualEntry": "Manual entry code",
    "auth.enterCode": "Enter 6-digit code",
    "auth.verifying": "Verifying...",
    "auth.verifyButton": "Verify and Continue",
    "auth.cantAccess": "Can't access your app? Reset MFA",
    "auth.backToLogin": "Back to login",
    "auth.passwordResetSent": "Password sent to your email",
    "auth.passwordResetError": "Failed to send password reset email",
    "auth.enterEmailFirst": "Please enter your email first",
    
    // Pivot Table Page
    "pivotTable.title": "Transaction Pivot Table",
    "pivotTable.subtitle": "Analyze transaction data with pivot tables",
    "pivotTable.configuration": "Pivot Configuration",
    "pivotTable.rowField": "Row Field",
    "pivotTable.columnField": "Column Field",
    "pivotTable.valueField": "Value Field",
    "pivotTable.aggregation": "Aggregation",
    "pivotTable.sum": "Sum",
    "pivotTable.count": "Count",
    "pivotTable.average": "Average",
    "pivotTable.min": "Minimum",
    "pivotTable.max": "Maximum",
    "pivotTable.generate": "Generate",
    "pivotTable.result": "Pivot Table Result",
    "pivotTable.total": "Total",
    
    // Shift Session
    "shiftSession": "Shift Session",
    "openShift": "Open Shift",
    "closeShift": "Close Shift",
    "shiftOpenedAt": "Shift Opened At",
    "closingBalance": "Closing Balance",
    "receiptImage": "Receipt Image",
    "uploadImage": "Upload Image",
    "changeImage": "Change Image",
    "noShiftAssignment": "No Shift Assignment",
    "noShiftAssignmentMessage": "You are not assigned to a shift today",
    "shiftOpenedSuccessfully": "Shift opened successfully",
    "shiftClosedSuccessfully": "Shift closed successfully",
    "imageUploadedSuccessfully": "Image uploaded successfully",
    "userNotAuthenticated": "User not authenticated",
    "userName": "User Name",
    "weekday": "Day",
    "hijriDate": "Hijri Date",
    "gregorianDate": "Gregorian Date",
    "date": "Date",
    "time": "Time",
    "success": "Success",
    "error": "Error",
    "loading": "Loading",
    
    // Shift Follow-Up
    "Shift Follow-Up": "Shift Follow-Up",
    "Refresh": "Refresh",
    "Shift Name": "Shift Name",
    "Start Time": "Start Time",
    "End Time": "End Time",
    "Assigned Person": "Assigned Person",
    "Status": "Status",
    "Notes": "Notes",
    "Actions": "Actions",
    "Select User": "Select User",
    "Not Started": "Not Started",
    "Open": "Open",
    "Closed": "Closed",
    "Unknown": "Unknown",
    "No shift assignments found for this date": "No shift assignments found for this date",
    "Failed to load users": "Failed to load users",
    "Failed to load shift assignments": "Failed to load shift assignments",
    "Please select a user": "Please select a user",
    "Shift assignment updated successfully": "Shift assignment updated successfully",
    "Failed to update shift assignment": "Failed to update shift assignment",
    "shiftFollowUp.title": "Shift Follow-Up",
    "shiftFollowUp.selectDate": "Select Date",
    "shiftFollowUp.refresh": "Refresh",
    "shiftFollowUp.shiftName": "Shift Name",
    "shiftFollowUp.assignedPerson": "Assigned Person",
    "shiftFollowUp.status": "Status",
    "shiftFollowUp.actions": "Actions",
    "shiftFollowUp.edit": "Edit",
    "shiftFollowUp.save": "Save",
    "shiftFollowUp.cancel": "Cancel",
    "shiftFollowUp.selectUser": "Select User",
    "shiftFollowUp.noAssignments": "No shift assignments found for this date",
    "shiftFollowUp.open": "Open",
    "shiftFollowUp.closed": "Closed",
    "shiftFollowUp.notStarted": "Not Started",
    "shiftFollowUp.editSuccess": "Shift assignment updated successfully",
    "shiftFollowUp.editError": "Failed to update shift assignment",
    "shiftDashboard.title": "Shift Dashboard",
    "shiftDashboard.loading": "Loading...",
    "shiftDashboard.totalShifts": "Total Shifts",
    "shiftDashboard.activeShifts": "Active",
    "shiftDashboard.totalAssignments": "Total Assignments",
    "shiftDashboard.openSessions": "Open Sessions",
    "shiftDashboard.closedSessions": "Closed Sessions",
    "shiftDashboard.pendingSessions": "Pending Sessions",
    "shiftDashboard.recentAssignments": "Recent Assignments",
    "shiftDashboard.noAssignments": "No assignments found",
    
    // Shift Setup Page
    "shiftSetup.title": "Shift Setup",
    "shiftSetup.addTitle": "Add New Shift",
    "shiftSetup.editTitle": "Edit Shift",
    "shiftSetup.shiftName": "Shift Name",
    "shiftSetup.shiftNamePlaceholder": "Enter shift name",
    "shiftSetup.shiftZone": "Shift Zone",
    "shiftSetup.selectShiftZone": "Select shift zone...",
    "shiftSetup.searchOrAddNew": "Search or add new...",
    "shiftSetup.addNewZone": "Add",
    "shiftSetup.shiftType": "Shift Type",
    "shiftSetup.selectShiftType": "Select shift type...",
    "shiftSetup.sales": "Sales",
    "shiftSetup.support": "Support",
    "shiftSetup.startTime": "Start Time",
    "shiftSetup.endTime": "End Time",
    "shiftSetup.color": "Shift Color",
    "shiftSetup.jobPositions": "Job Positions",
    "shiftSetup.shiftAdmins": "Shift Admins",
    "shiftSetup.addShift": "Add Shift",
    "shiftSetup.updateShift": "Update Shift",
    "shiftSetup.saving": "Saving...",
    "shiftSetup.cancel": "Cancel",
    "shiftSetup.shiftsList": "Shifts List",
    "shiftSetup.zone": "Zone",
    "shiftSetup.type": "Type",
    "shiftSetup.actions": "Actions",
    "shiftSetup.noPositionsAssigned": "No positions assigned",
    "shiftSetup.noAdminsAssigned": "No admins assigned",
    "shiftSetup.noShiftsFound": "No shifts found. Add your first shift above.",
    "shiftSetup.deleteConfirm": "Are you sure you want to delete this shift?",
    "shiftSetup.zoneAddedSuccess": "Shift zone added successfully",
    "shiftSetup.addedSuccess": "Shift added successfully",
    "shiftSetup.updatedSuccess": "Shift updated successfully",
    "shiftSetup.deletedSuccess": "Shift deleted successfully",
    "shiftSetup.fillAllFields": "Please fill all required fields",
    "shiftSetup.errorFetchShifts": "Failed to load shifts",
    "shiftSetup.errorFetchZones": "Failed to load shift zones",
    "shiftSetup.errorFetchPositions": "Failed to load job positions",
    "shiftSetup.errorFetchUsers": "Failed to load users",
    "shiftSetup.errorAddZone": "Failed to add shift zone",
    "shiftSetup.errorSaveShift": "Failed to save shift",
    "shiftSetup.errorDeleteShift": "Failed to delete shift",
    "shiftSetup.noZonesFound": "No shift zones found.",
    
    // Common
    "common.success": "Success",
    "common.error": "Error",
    "common.loading": "Loading...",
    "common.all": "All",
    "common.confirm": "Confirm",
    "common.cancel": "Cancel",
    "common.back": "Back",
    "common.clearFilters": "Clear Filters",
  },
  ar: {
    // Header
    "app.name": "إدارة",
    "theme.toggle": "تبديل السمة",
    "language.toggle": "تبديل اللغة",
    
    // Sidebar Groups
    "sidebar.reports": "التقارير ولوحة التحكم",
    "sidebar.entry": "الإدخال",
    "sidebar.setup": "الإعداد",
    "sidebar.admin": "الإدارة",
    
    // Menu Items
    "menu.dashboard": "لوحة التحكم",
    "menu.reports": "التقارير",
    
    // Reports Page
    "reports.title": "التقارير",
    "reports.subtitle": "اختر تقريرًا لعرض المعاملات وتشغيله",
    "reports.revenueByBrandType.name": "الإيرادات حسب نوع العلامة التجارية",
    "reports.revenueByBrandType.description": "حساب إجمالي الإيرادات بناءً على نوع العلامة التجارية",
    "reports.costByBrandType.name": "التكلفة حسب نوع العلامة التجارية",
    "reports.costByBrandType.description": "حساب إجمالي التكلفة بناءً على نوع العلامة التجارية",
    "reports.viewReport": "عرض التقرير",
    
    // Revenue by Brand Type Report
    "revenueReport.title": "تقرير الإيرادات حسب نوع العلامة التجارية",
    "revenueReport.parameters": "معاملات التقرير",
    "revenueReport.dateFrom": "من تاريخ",
    "revenueReport.dateTo": "إلى تاريخ",
    "revenueReport.brandType": "نوع العلامة التجارية",
    "revenueReport.allBrandTypes": "جميع أنواع العلامات التجارية",
    "revenueReport.selectBrandType": "اختر نوع العلامة التجارية",
    "revenueReport.runReport": "تشغيل التقرير",
    "revenueReport.exportCSV": "تصدير CSV",
    "revenueReport.print": "طباعة",
    "revenueReport.reportDetails": "تفاصيل التقرير",
    "revenueReport.generatedOn": "تم إنشاؤه في",
    "revenueReport.selectionCriteria": "معايير الاختيار",
    "revenueReport.dateRange": "نطاق التاريخ",
    "revenueReport.to": "إلى",
    "revenueReport.reportData": "بيانات التقرير",
    "revenueReport.brandTypeName": "اسم نوع العلامة التجارية",
    "revenueReport.totalRevenue": "إجمالي الإيرادات",
    "revenueReport.transactionCount": "عدد المعاملات",
    "revenueReport.total": "المجموع",
    "revenueReport.average": "المتوسط",
    "revenueReport.noData": "لا توجد بيانات متاحة للمعايير المحددة",
    
    // Cost by Brand Type Report
    "costReport.title": "تقرير التكلفة حسب نوع العلامة التجارية",
    "costReport.parameters": "معاملات التقرير",
    "costReport.dateFrom": "من تاريخ",
    "costReport.dateTo": "إلى تاريخ",
    "costReport.brandType": "نوع العلامة التجارية",
    "costReport.allBrandTypes": "جميع أنواع العلامات التجارية",
    "costReport.selectBrandType": "اختر نوع العلامة التجارية",
    "costReport.runReport": "تشغيل التقرير",
    "costReport.exportCSV": "تصدير CSV",
    "costReport.print": "طباعة",
    "costReport.reportDetails": "تفاصيل التقرير",
    "costReport.generatedOn": "تم إنشاؤه في",
    "costReport.selectionCriteria": "معايير الاختيار",
    "costReport.dateRange": "نطاق التاريخ",
    "costReport.to": "إلى",
    "costReport.reportData": "بيانات التقرير",
    "costReport.brandTypeName": "اسم نوع العلامة التجارية",
    "costReport.totalCost": "إجمالي التكلفة",
    "costReport.transactionCount": "عدد المعاملات",
    "costReport.total": "المجموع",
    "costReport.average": "المتوسط",
    "costReport.noData": "لا توجد بيانات متاحة للمعايير المحددة",
    "menu.transactions": "بيانات المعاملات",
    "menu.pivotTable": "جدول محوري",
    "menu.loadData": "تحميل البيانات من Excel",
    "menu.clearData": "حذف البيانات",
    "menu.reportsSetup": "إعداد التقارير",
    "menu.apiConfig": "إعدادات API",
    "menu.excelSetup": "إعدادات Excel",
    "menu.tableConfig": "إعدادات الجداول",
    "menu.userSetup": "إعداد المستخدمين",
    "menu.customerSetup": "إعداد العملاء",
    "menu.customerProfile": "ملف العملاء",
    "menu.customerTotals": "إجماليات العملاء",
    "menu.brandSetup": "إعداد الماركات",
    "menu.brandType": "نوع الماركة",
    "menu.productSetup": "إعداد المنتجات",
    
    // Ticket Details Page
    "ticketDetails.backToTickets": "العودة إلى التذاكر",
    "ticketDetails.loading": "جاري تحميل تفاصيل التذكرة...",
    "ticketDetails.notFound": "التذكرة غير موجودة",
    "ticketDetails.ticketNumber": "رقم التذكرة #",
    "ticketDetails.department": "القسم:",
    "ticketDetails.created": "تاريخ الإنشاء:",
    "ticketDetails.createdBy": "أنشئ بواسطة:",
    "ticketDetails.email": "البريد الإلكتروني:",
    "ticketDetails.description": "الوصف",
    "ticketDetails.commentsUpdates": "التعليقات والتحديثات",
    "ticketDetails.noComments": "لا توجد تعليقات بعد",
    "ticketDetails.addCommentPlaceholder": "أضف تعليقاً...",
    "ticketDetails.addComment": "إضافة تعليق",
    "ticketDetails.internalNote": "ملاحظة داخلية",
    "ticketDetails.success": "نجح",
    "ticketDetails.commentAdded": "تم إضافة التعليق بنجاح",
    "ticketDetails.error": "خطأ",
    
    // Customer Setup Page
    "customerSetup.title": "إعداد العملاء",
    "customerSetup.subtitle": "إدارة معلومات العملاء",
    "customerSetup.phone": "الهاتف",
    "customerSetup.name": "الاسم",
    "customerSetup.creationDate": "تاريخ الإنشاء",
    "customerSetup.updatedDate": "تاريخ التحديث",
    "customerSetup.updatedBy": "تم التحديث بواسطة",
    "customerSetup.status": "الحالة",
    "customerSetup.blocked": "محظور",
    "customerSetup.blockReason": "سبب الحظر",
    "customerSetup.actions": "الإجراءات",
    "customerSetup.edit": "تعديل",
    "customerSetup.active": "نشط",
    "customerSetup.disabled": "معطل",
    "customerSetup.editCustomer": "تعديل العميل",
    "customerSetup.customerName": "اسم العميل",
    "customerSetup.customerNamePlaceholder": "أدخل اسم العميل",
    "customerSetup.selectStatus": "اختر الحالة",
    "customerSetup.blockReasonPlaceholder": "أدخل سبب الحظر (إن وجد)",
    "customerSetup.cancel": "إلغاء",
    "customerSetup.save": "حفظ التغييرات",
    "customerSetup.saving": "جاري الحفظ...",
    "customerSetup.success": "تم تحديث العميل بنجاح",
    "customerSetup.error": "فشل تحديث العميل",
    "customerSetup.loading": "جاري تحميل العملاء...",
    "customerSetup.noData": "لا يوجد عملاء",
    "customerSetup.clearAll": "مسح جميع العملاء",
    "customerSetup.clearConfirm": "هل أنت متأكد من حذف جميع العملاء؟",
    "customerSetup.cleared": "تم مسح جميع العملاء بنجاح",
    "customerSetup.filterByName": "تصفية بالاسم",
    "customerSetup.filterByPhone": "تصفية بالهاتف",
    "customerSetup.filterByBrand": "تصفية بالماركة",
    "customerSetup.filterByProduct": "تصفية بالمنتج",
    "customerSetup.totalSpend": "إجمالي الإنفاق",
    "customerSetup.viewTransactions": "عرض المعاملات",
    "customerSetup.viewSummary": "عرض الملخص",
    "customerSetup.customerTransactions": "معاملات العميل",
    "customerSetup.customerSummary": "ملخص العميل",
    "customerSetup.brand": "الماركة",
    "customerSetup.product": "المنتج",
    "customerSetup.lastTransaction": "آخر معاملة",
    "customerSetup.newCustomer": "عميل جديد",
    "customerSetup.lastTransactionDate": "آخر معاملة",
    "customerSetup.customers": "عملاء",
    "customerSetup.orderNumber": "رقم الطلب",
    "customerSetup.syncCustomers": "مزامنة العملاء",
    "customerSetup.missingCustomersFound": "تم العثور على عملاء مفقودين",
    "customerSetup.noMissingCustomers": "لم يتم العثور على عملاء مفقودين",
    "customerSetup.customersAdded": "عميل تمت إضافتهم بنجاح",
    "customerSetup.date": "التاريخ",
    "customerSetup.quantity": "الكمية",
    "customerSetup.paymentMethod": "طريقة الدفع",
    "customerSetup.paymentType": "نوع الدفع",
    "customerSetup.total": "الإجمالي",
    "customerSetup.noTransactions": "لا توجد معاملات",
    "customerSetup.totalTransactionsCount": "إجمالي المعاملات",
    "customerSetup.totalAmount": "المبلغ الإجمالي",
    "customerSetup.partnerId": "معرف الشريك",
    "customerSetup.notSynced": "غير متزامن",
    "customerSetup.addNew": "إضافة عميل جديد",
    "customerSetup.phonePlaceholder": "أدخل رقم الهاتف",
    "customerSetup.namePlaceholder": "أدخل اسم العميل",
    "customerSetup.created": "تم إنشاء العميل بنجاح",
    "customerSetup.updated": "تم تحديث العميل بنجاح",
    "customerSetup.deleted": "تم حذف العميل بنجاح",
    "customerSetup.deleteConfirm": "هل أنت متأكد من حذف هذا العميل؟",
    "customerSetup.fillAllFields": "الرجاء ملء جميع الحقول المطلوبة",
    "customerSetup.delete": "حذف",
    "customerSetup.customerUpdated": "تم تحديث العميل بنجاح",
    
    // Brand Setup Page
    "brandSetup.title": "إعداد الماركات",
    "brandSetup.brandName": "اسم الماركة",
    "brandSetup.status": "الحالة",
    "brandSetup.createdDate": "تاريخ الإنشاء",
    "brandSetup.updatedDate": "تاريخ التحديث",
    "brandSetup.actions": "الإجراءات",
    "brandSetup.addNew": "إضافة ماركة جديدة",
    "brandSetup.editBrand": "تعديل الماركة",
    "brandSetup.brandNamePlaceholder": "أدخل اسم الماركة",
    "brandSetup.active": "نشط",
    "brandSetup.inactive": "غير نشط",
    "brandSetup.cancel": "إلغاء",
    "brandSetup.save": "حفظ",
    "brandSetup.saving": "جاري الحفظ...",
    "brandSetup.created": "تم إنشاء الماركة بنجاح",
    "brandSetup.updated": "تم تحديث الماركة بنجاح",
    "brandSetup.deleted": "تم حذف الماركة بنجاح",
    "brandSetup.deleteConfirm": "هل أنت متأكد من حذف هذه الماركة؟",
    "brandSetup.noData": "لا توجد ماركات",
    "brandSetup.brandType": "نوع الماركة",
    "brandSetup.selectBrandType": "اختر نوع الماركة",
    "brandSetup.noBrandType": "بدون نوع",
    
    // Brand Type Page
    "brandType.title": "نوع الماركة",
    "brandType.brandCode": "كود الماركة",
    "brandType.brandName": "اسم الماركة",
    "brandType.status": "الحالة",
    "brandType.createdDate": "تاريخ الإنشاء",
    "brandType.updatedDate": "تاريخ التحديث",
    "brandType.actions": "الإجراءات",
    "brandType.addNew": "إضافة نوع ماركة جديد",
    "brandType.editBrand": "تعديل نوع الماركة",
    "brandType.brandCodePlaceholder": "أدخل كود الماركة",
    "brandType.brandNamePlaceholder": "أدخل اسم الماركة",
    "brandType.active": "نشط",
    "brandType.inactive": "غير نشط",
    "brandType.cancel": "إلغاء",
    "brandType.save": "حفظ",
    "brandType.saving": "جاري الحفظ...",
    "brandType.created": "تم إنشاء نوع الماركة بنجاح",
    "brandType.updated": "تم تحديث نوع الماركة بنجاح",
    "brandType.deleted": "تم حذف نوع الماركة بنجاح",
    "brandType.deleteConfirm": "هل أنت متأكد من حذف نوع الماركة هذا؟",
    "brandType.noData": "لا توجد أنواع ماركات",
    "brandType.filterByCode": "تصفية حسب كود الماركة",
    "brandType.filterByName": "تصفية حسب اسم الماركة",
    "brandType.filterByCodePlaceholder": "ابحث عن كود الماركة...",
    "brandType.filterByNamePlaceholder": "ابحث عن اسم الماركة...",
    "brandType.noMatches": "لا توجد أنواع ماركات تطابق الفلاتر",
    
    // Product Setup Page
    "productSetup.title": "إعداد المنتجات",
    "productSetup.productId": "معرف المنتج",
    "productSetup.productName": "اسم المنتج",
    "productSetup.productPrice": "سعر المنتج",
    "productSetup.productCost": "تكلفة المنتج",
    "productSetup.brand": "الماركة",
    "productSetup.brandPlaceholder": "أدخل اسم الماركة",
    "productSetup.status": "الحالة",
    "productSetup.createdDate": "تاريخ الإنشاء",
    "productSetup.actions": "الإجراءات",
    "productSetup.addNew": "إضافة منتج جديد",
    "productSetup.editProduct": "تعديل المنتج",
    "productSetup.productIdPlaceholder": "أدخل معرف المنتج (اختياري)",
    "productSetup.productNamePlaceholder": "أدخل اسم المنتج",
    "productSetup.productPricePlaceholder": "أدخل سعر المنتج",
    "productSetup.productCostPlaceholder": "أدخل تكلفة المنتج",
    "productSetup.active": "نشط",
    "productSetup.inactive": "غير نشط",
    "productSetup.cancel": "إلغاء",
    "productSetup.save": "حفظ",
    "productSetup.created": "تم إنشاء المنتج بنجاح",
    "productSetup.updated": "تم تحديث المنتج بنجاح",
    "productSetup.deleted": "تم حذف المنتج بنجاح",
    "productSetup.deleteConfirm": "هل أنت متأكد من حذف هذا المنتج؟",
    "productSetup.filterByName": "تصفية حسب اسم المنتج",
    "productSetup.filterByBrand": "تصفية حسب الماركة",
    "productSetup.noData": "لا توجد منتجات",
    "productSetup.viewGrid": "شبكة",
    "productSetup.viewTree": "شجرة",
    "productSetup.noBrand": "بدون ماركة",
    "productSetup.product": "منتج",
    "productSetup.products": "منتجات",
    "productSetup.moreDetails": "تفاصيل أكثر",
    "productSetup.stock": "المخزون",
    "productSetup.pricing": "التسعير",
    "productSetup.freeCoins": "النقاط المجانية",
    "productSetup.options": "الخيارات",
    "productSetup.customerGroupPrices": "أسعار مجموعات العملاء",
    "productSetup.discounts": "التخفيضات",
    "productSetup.seo": "تحسين محركات البحث",
    "productSetup.quantity": "الكمية",
    "productSetup.quantityPlaceholder": "أدخل الكمية",
    "productSetup.sku": "رمز المنتج",
    "productSetup.skuPlaceholder": "أدخل رمز المنتج",
    "productSetup.location": "الموقع",
    "productSetup.locationPlaceholder": "أدخل الموقع",
    "productSetup.model": "الموديل",
    "productSetup.modelPlaceholder": "أدخل الموديل",
    "productSetup.minQuantity": "الحد الأدنى للكمية",
    "productSetup.minQuantityPlaceholder": "أدخل الحد الأدنى للكمية",
    "productSetup.stockStatus": "حالة المخزون",
    "productSetup.inStock": "متوفر",
    "productSetup.outOfStock": "غير متوفر",
    "productSetup.preOrder": "طلب مسبق",
    "productSetup.specialPrice": "سعر خاص",
    "productSetup.specialPricePlaceholder": "أدخل السعر الخاص",
    "productSetup.specialStartDate": "تاريخ بدء السعر الخاص",
    "productSetup.specialEndDate": "تاريخ انتهاء السعر الخاص",
    "productSetup.taxClass": "فئة الضريبة",
    "productSetup.taxClassPlaceholder": "أدخل فئة الضريبة",
    "productSetup.defaultTax": "الضريبة الافتراضية",
    "productSetup.noTax": "بدون ضريبة",
    "productSetup.coinsGiven": "النقاط الممنوحة",
    "productSetup.coinsGivenPlaceholder": "أدخل النقاط الممنوحة",
    "productSetup.coinsRedeemed": "النقاط المستردة",
    "productSetup.coinsRedeemedPlaceholder": "أدخل النقاط المستردة",
    "productSetup.optionName": "اسم الخيار",
    "productSetup.optionNamePlaceholder": "أدخل اسم الخيار",
    "productSetup.optionValue": "قيمة الخيار",
    "productSetup.optionValuePlaceholder": "أدخل قيمة الخيار",
    "productSetup.required": "مطلوب",
    "productSetup.addOption": "إضافة خيار",
    "productSetup.customerGroup": "مجموعة العملاء",
    "productSetup.customerGroupPlaceholder": "أدخل مجموعة العملاء",
    "productSetup.groupPrice": "سعر المجموعة",
    "productSetup.groupPricePlaceholder": "أدخل سعر المجموعة",
    "productSetup.addGroupPrice": "إضافة سعر مجموعة",
    "productSetup.discountGroup": "مجموعة التخفيض",
    "productSetup.discountGroupPlaceholder": "أدخل مجموعة التخفيض",
    "productSetup.discountQuantity": "كمية التخفيض",
    "productSetup.discountQuantityPlaceholder": "أدخل كمية التخفيض",
    "productSetup.discountPriority": "أولوية التخفيض",
    "productSetup.discountPriorityPlaceholder": "أدخل أولوية التخفيض",
    "productSetup.discountPrice": "سعر التخفيض",
    "productSetup.discountPricePlaceholder": "أدخل سعر التخفيض",
    "productSetup.discountStartDate": "تاريخ بدء التخفيض",
    "productSetup.discountEndDate": "تاريخ انتهاء التخفيض",
    "productSetup.addDiscount": "إضافة تخفيض",
    "productSetup.metaTitle": "عنوان التعريف",
    "productSetup.metaTitlePlaceholder": "أدخل عنوان التعريف",
    "productSetup.metaDescription": "وصف التعريف",
    "productSetup.metaDescriptionPlaceholder": "أدخل وصف التعريف",
    "productSetup.metaKeywords": "كلمات مفتاحية",
    "productSetup.metaKeywordsPlaceholder": "أدخل الكلمات المفتاحية",
    "productSetup.mobile": "الهاتف المحمول",
    "productSetup.enabled": "مُفعّل",
    "productSetup.disabled": "معطّل",
    "productSetup.on": "تشغيل",
    "productSetup.off": "إيقاف",
    "productSetup.notifyQty": "نقطة إعادة الطلب",
    "productSetup.notifyQtyPlaceholder": "أدخل كمية نقطة إعادة الطلب",
    "productSetup.maxQuantity": "الحد الأقصى للكمية",
    "productSetup.maxQuantityPlaceholder": "أدخل الحد الأقصى للكمية",
    "productSetup.minCoins": "الحد الأدنى للنقاط",
    "productSetup.minCoinsPlaceholder": "أدخل الحد الأدنى للنقاط",
    "productSetup.maxCoins": "الحد الأقصى للنقاط",
    "productSetup.maxCoinsPlaceholder": "أدخل الحد الأقصى للنقاط",
    "productSetup.productInformation": "معلومات المنتج",
    "productSetup.stockManagement": "إدارة المخزون",
    "productSetup.barcode": "الباركود",
    "productSetup.category": "الفئة",
    "productSetup.weight": "الوزن",
    "productSetup.supplier": "المورد",
    "productSetup.description": "الوصف",
    "productSetup.notes": "ملاحظات",
    "productSetup.stockQuantity": "كمية المخزون",
    "productSetup.reorderPoint": "نقطة إعادة الطلب",
    "productSetup.taxIncluded": "شامل الضريبة",
    "productSetup.taxExcluded": "غير شامل الضريبة",
    "productSetup.min": "الحد الأدنى",
    "productSetup.max": "الحد الأقصى",
    "productSetup.salePoints": "نقاط البيع",
    "productSetup.purchasePoints": "نقاط الشراء",
    "productSetup.allGroups": "جميع المجموعات",
    "productSetup.vip": "VIP",
    "productSetup.store": "المتجر",
    "productSetup.purpleStore": "المتجر البنفسجي",
    "productSetup.allCustomerGroups": "جميع مجموعات العملاء",
    "productSetup.fixed": "ثابت",
    "productSetup.percentage": "%",
    "productSetup.coinsNumber": "عدد النقاط",
    "productSetup.coinsPrice": "سعر النقاط",
    "productSetup.optionId": "معرف الخيار",
    "productSetup.groupName": "اسم المجموعة",
    "productSetup.price": "السعر",
    "productSetup.discountType": "نوع الخصم",
    "productSetup.salePrice": "سعر البيع",
    "productSetup.purchasePrice": "سعر الشراء",
    "productSetup.amountType": "نوع المبلغ",
    "productSetup.amount": "المبلغ",
    "productSetup.startDate": "تاريخ البداية",
    "productSetup.endDate": "تاريخ النهاية",
    "productSetup.arabic": "عربي",
    "productSetup.english": "إنجليزي",
    "productSetup.leadtime": "مدة التسليم (بالأيام)",
    "productSetup.safetyStock": "مخزون الأمان",
    "productSetup.abcAnalysis": "تحليل ABC",
    
    // Upload Log
    "uploadLog.title": "سجل التحميلات",
    "uploadLog.subtitle": "عرض سجل وحالة تحميل البيانات",
    "uploadLog.date": "التاريخ",
    "uploadLog.fileName": "اسم الملف",
    "uploadLog.uploadedBy": "تم التحميل بواسطة",
    "uploadLog.status": "الحالة",
    "uploadLog.recordsProcessed": "السجلات المعالجة",
    "uploadLog.newCustomers": "عملاء جدد",
    "uploadLog.excelDates": "تواريخ Excel",
    "uploadLog.errors": "الأخطاء",
    "uploadLog.excelDatesTitle": "تواريخ Excel في الملف",
    "uploadLog.view": "عرض",
    "uploadLog.summary": "ملخص",
    "uploadLog.viewSummary": "عرض الملخص",
    "uploadLog.uploadSummary": "ملخص الرفع",
    "uploadLog.summaryDescription": "ملخص عملية الرفع",
    "uploadLog.totalValue": "القيمة الإجمالية",
    "uploadLog.newProducts": "المنتجات الجديدة",
    "uploadLog.dateRange": "النطاق الزمني",
    "uploadLog.completed": "مكتمل",
    "uploadLog.failed": "فشل",
    "uploadLog.processing": "جاري المعالجة",
    "uploadLog.close": "إغلاق",
    "uploadLog.updateBankFees": "تحديث رسوم البنك",
    "uploadLog.updatingBankFees": "جاري تحديث رسوم البنك...",
    "uploadLog.bankFeesUpdated": "تم تحديث رسوم البنك بنجاح",
    "uploadLog.bankFeesUpdateError": "خطأ في تحديث رسوم البنك",
    
    // Dashboard - Sales Analytics
    "dashboard.title": "لوحة المبيعات",
    "dashboard.subtitle": "نظرة عامة على المبيعات",
    "dashboard.totalSales": "إجمالي المبيعات",
    "dashboard.totalProfit": "إجمالي الأرباح",
    "dashboard.transactions": "المعاملات",
    "dashboard.avgOrderValue": "متوسط قيمة الطلب",
    "dashboard.salesTrend": "اتجاه المبيعات",
    "dashboard.topBrands": "أفضل العلامات التجارية",
    "dashboard.topCategories": "أفضل 5 فئات منتجات",
    "dashboard.topProducts": "أفضل 10 منتجات",
    "dashboard.paymentMethods": "طرق الدفع",
    "dashboard.paymentBrands": "علامات الدفع التجارية",
    "dashboard.monthComparison": "مقارنة شهرية",
    "dashboard.productSummary": "ملخص مبيعات المنتجات",
    "dashboard.incomeStatement": "قائمة الدخل",
    "dashboard.recentTransactions": "المعاملات الأخيرة",
    "dashboard.date": "التاريخ",
    "dashboard.customer": "العميل",
    "dashboard.brand": "العلامة التجارية",
    "dashboard.product": "المنتج",
    "dashboard.category": "الفئة",
    "dashboard.amount": "المبلغ",
    "dashboard.profit": "الربح",
    "dashboard.sales": "المبيعات",
    "dashboard.viewAll": "عرض جميع المعاملات",
    "dashboard.loading": "جاري تحميل بيانات لوحة التحكم...",
    "dashboard.noData": "لا توجد بيانات مبيعات متاحة",
    "dashboard.yesterday": "أمس",
    "dashboard.thisMonth": "هذا الشهر",
    "dashboard.lastMonth": "الشهر الماضي",
    "dashboard.dateRange": "نطاق التاريخ",
    "dashboard.from": "من",
    "dashboard.to": "إلى",
    "dashboard.apply": "تطبيق",
    "dashboard.couponSales": "مبيعات الكوبونات",
    "dashboard.salesPlusCoupon": "المبيعات + الكوبونات",
    "dashboard.costOfSales": "تكلفة المبيعات",
    "dashboard.ePaymentCharges": "رسوم الدفع الإلكتروني",
    "dashboard.netSales": "صافي المبيعات",
    "dashboard.totalSalesWithDiscount": "إجمالي المبيعات (تشمل التخفيضات)",
    "dashboard.discountCoupons": "كوبونات التخفيض",
    "dashboard.shipping": "الشحن",
    "dashboard.taxes": "الضرائب",
    "dashboard.totalPoints": "إجمالي النقاط",
    "dashboard.pointsCost": "تكلفة النقاط",
    "dashboard.pointTransactions": "معاملات النقاط",
    "dashboard.pointTransactionsEmpty": "لا توجد معاملات نقاط",
    "dashboard.customerPurchases": "ملخص مشتريات العملاء",
    "dashboard.customerName": "اسم العميل",
    "dashboard.totalValue": "القيمة الإجمالية",
    "dashboard.transactionCount": "عدد المعاملات",
    "dashboard.filterProduct": "تصفية حسب المنتج",
    "dashboard.filterCategory": "تصفية حسب الفئة",
    "dashboard.filterBrand": "تصفية حسب العلامة التجارية",
    "dashboard.filterCustomer": "تصفية حسب العميل",
    "dashboard.allProducts": "جميع المنتجات",
    "dashboard.allCategories": "جميع الفئات",
    "dashboard.allBrands": "جميع العلامات التجارية",
    "dashboard.allCustomers": "جميع العملاء",
    "dashboard.quantity": "الكمية",
    "dashboard.loadingInitializing": "جاري التهيئة...",
    "dashboard.loadingTransactions": "جاري تحميل المعاملات...",
    "dashboard.loadingCalculatingStats": "جاري حساب الإحصائيات...",
    "dashboard.loadingProcessingData": "جاري معالجة البيانات...",
    "dashboard.loadingCompleting": "جاري الإنهاء...",
    "dashboard.crmReminder": "تذكير إدارة علاقات العملاء",
    "dashboard.notes": "ملاحظات",
    "dashboard.nextAction": "الإجراء التالي",
    "dashboard.reminderDate": "تاريخ التذكير",
    "dashboard.noReminders": "لا توجد تذكيرات في الوقت الحالي",
    "dashboard.orderNumber": "رقم الطلب",
    "dashboard.paymentMethod": "طريقة الدفع",
    "dashboard.status": "الحالة",
    "dashboard.total": "الإجمالي",
    "dashboard.coinsByBrand": "إجمالى الكوينز المباعة",
    "dashboard.brandName": "اسم الماركة",
    "dashboard.totalCoins": "إجمالي النقاط",
    "dashboard.noCoinsData": "لا توجد بيانات نقاط متاحة",
    
    // Transactions Page
    "transactions.title": "جميع المعاملات",
    "transactions.subtitle": "عرض وإدارة بيانات المعاملات",
    "transactions.export": "تصدير",
    "transactions.search": "البحث في المعاملات...",
    "transactions.searchCustomerProduct": "بحث عن عميل أو منتج...",
    "transactions.filterByPhone": "تصفية حسب رقم الهاتف...",
    "transactions.filterByOrderNumber": "تصفية حسب رقم الطلب...",
    "transactions.orderNumber": "رقم الطلب",
    "transactions.userName": "اسم المستخدم",
    "transactions.paymentMethod": "طريقة الدفع",
    "transactions.paymentType": "نوع الدفع",
    "transactions.customerPhone": "هاتف العميل",
    "transactions.costPrice": "سعر التكلفة",
    "transactions.unitPrice": "سعر الوحدة",
    "transactions.costSold": "التكلفة المباعة",
    "transactions.qty": "الكمية",
    "transactions.coinsNumber": "رقم العملات",
    "transactions.vendorName": "اسم المورد",
    "transactions.orderStatus": "حالة الطلب",
    
    // Clear Data Page
    "clearData.title": "حذف البيانات",
    "clearData.subtitle": "حذف البيانات من الجداول حسب نطاق التاريخ",
    "clearData.selectTable": "اختر الجدول",
    "clearData.selectTablePlaceholder": "اختر جدولاً...",
    "clearData.fromDate": "من تاريخ",
    "clearData.toDate": "إلى تاريخ",
    "clearData.clearButton": "حذف البيانات",
    "clearData.confirmTitle": "تأكيد حذف البيانات",
    "clearData.confirmMessage": "هل أنت متأكد من حذف جميع السجلات من {table} بين {fromDate} و {toDate}؟ لا يمكن التراجع عن هذا الإجراء.",
    "clearData.cancel": "إلغاء",
    "clearData.confirm": "تأكيد الحذف",
    "clearData.success": "تم حذف البيانات بنجاح",
    "clearData.error": "خطأ في حذف البيانات",
    "clearData.selectTableFirst": "الرجاء اختيار جدول أولاً",
    "clearData.selectDates": "الرجاء اختيار كلا التاريخين (من وإلى)",
    
    // Welcome/Landing Page
    "welcome.title": "مرحباً بك في إدارة",
    "welcome.subtitle": "نظام إدارة الأعمال الخاص بك",
    
    // Auth Page
    "auth.welcome": "مرحباً بك في إدارة",
    "auth.signIn": "تسجيل الدخول بيانات الاعتماد الخاصة بك",
    "auth.changePassword": "تغيير كلمة المرور",
    "auth.setupMFA": "إعداد المصادقة الثنائية",
    "auth.verifyMFA": "أدخل الرمز من تطبيق المصادقة",
    "auth.email": "البريد الإلكتروني",
    "auth.emailPlaceholder": "you@example.com",
    "auth.password": "كلمة المرور",
    "auth.passwordPlaceholder": "أدخل كلمة المرور",
    "auth.newPassword": "كلمة المرور الجديدة",
    "auth.newPasswordPlaceholder": "أدخل كلمة المرور الجديدة",
    "auth.confirmPassword": "تأكيد كلمة المرور",
    "auth.confirmPasswordPlaceholder": "أكد كلمة المرور الجديدة",
    "auth.signInButton": "تسجيل الدخول",
    "auth.signingIn": "جاري تسجيل الدخول...",
    "auth.changePasswordButton": "تغيير كلمة المرور",
    "auth.updating": "جاري التحديث...",
    "auth.resetPassword": "نسيت كلمة المرور؟",
    "auth.resetPasswordSending": "جاري الإرسال...",
    "auth.scanQR": "امسح رمز QR باستخدام تطبيق المصادقة",
    "auth.manualEntry": "رمز الإدخال اليدوي",
    "auth.enterCode": "أدخل الرمز المكون من 6 أرقام",
    "auth.verifying": "جاري التحقق...",
    "auth.verifyButton": "تحقق ومتابعة",
    "auth.cantAccess": "لا يمكنك الوصول إلى تطبيقك؟ إعادة تعيين المصادقة الثنائية",
    "auth.backToLogin": "العودة لتسجيل الدخول",
    "auth.passwordResetSent": "تم إرسال كلمة المرور إلى بريدك الإلكتروني",
    "auth.passwordResetError": "فشل إرسال بريد إعادة تعيين كلمة المرور",
    "auth.enterEmailFirst": "الرجاء إدخال بريدك الإلكتروني أولاً",
    
    // Pivot Table Page
    "pivotTable.title": "جدول محوري للمعاملات",
    "pivotTable.subtitle": "تحليل بيانات المعاملات باستخدام الجداول المحورية",
    "pivotTable.configuration": "تكوين الجدول المحوري",
    "pivotTable.rowField": "حقل الصفوف",
    "pivotTable.columnField": "حقل الأعمدة",
    "pivotTable.valueField": "حقل القيمة",
    "pivotTable.aggregation": "التجميع",
    "pivotTable.sum": "المجموع",
    "pivotTable.count": "العدد",
    "pivotTable.average": "المتوسط",
    "pivotTable.min": "الحد الأدنى",
    "pivotTable.max": "الحد الأقصى",
    "pivotTable.generate": "إنشاء",
    "pivotTable.result": "نتيجة الجدول المحوري",
    "pivotTable.total": "المجموع",
    
    // Shift Session
    "shiftSession": "جلسة الوردية",
    "openShift": "فتح الوردية",
    "closeShift": "إغلاق الوردية",
    "shiftOpenedAt": "تم فتح الوردية في",
    "closingBalance": "الرصيد الختامي",
    "receiptImage": "صورة الإيصال",
    "uploadImage": "رفع صورة",
    "changeImage": "تغيير الصورة",
    "noShiftAssignment": "لا توجد وردية مخصصة",
    "noShiftAssignmentMessage": "أنت غير مخصص لوردية اليوم",
    "shiftOpenedSuccessfully": "تم فتح الوردية بنجاح",
    "shiftClosedSuccessfully": "تم إغلاق الوردية بنجاح",
    "imageUploadedSuccessfully": "تم رفع الصورة بنجاح",
    "userNotAuthenticated": "المستخدم غير مصرح له",
    "userName": "اسم المستخدم",
    "weekday": "اليوم",
    "hijriDate": "التاريخ الهجري",
    "gregorianDate": "التاريخ الميلادي",
    "date": "التاريخ",
    "time": "الوقت",
    "success": "نجاح",
    "error": "خطأ",
    "loading": "جار التحميل",
    
    // Shift Follow-Up
    "Shift Follow-Up": "متابعة الورديات",
    "Refresh": "تحديث",
    "Shift Name": "اسم الوردية",
    "Start Time": "وقت البدء",
    "End Time": "وقت الانتهاء",
    "Assigned Person": "الموظف المخصص",
    "Status": "الحالة",
    "Notes": "ملاحظات",
    "Actions": "الإجراءات",
    "Select User": "اختر الموظف",
    "Not Started": "لم تبدأ",
    "Open": "مفتوحة",
    "Closed": "مغلقة",
    "Unknown": "غير معروف",
    "No shift assignments found for this date": "لا توجد ورديات مخصصة لهذا التاريخ",
    "Failed to load users": "فشل تحميل المستخدمين",
    "Failed to load shift assignments": "فشل تحميل الورديات المخصصة",
    "Please select a user": "الرجاء اختيار موظف",
    "Shift assignment updated successfully": "تم تحديث الوردية المخصصة بنجاح",
    "Failed to update shift assignment": "فشل تحديث الوردية المخصصة",
    "shiftFollowUp.title": "متابعة الورديات",
    "shiftFollowUp.selectDate": "اختر التاريخ",
    "shiftFollowUp.refresh": "تحديث",
    "shiftFollowUp.shiftName": "اسم الوردية",
    "shiftFollowUp.assignedPerson": "الشخص المعين",
    "shiftFollowUp.status": "الحالة",
    "shiftFollowUp.actions": "الإجراءات",
    "shiftFollowUp.edit": "تعديل",
    "shiftFollowUp.save": "حفظ",
    "shiftFollowUp.cancel": "إلغاء",
    "shiftFollowUp.selectUser": "اختر المستخدم",
    "shiftFollowUp.noAssignments": "لا توجد تعيينات ورديات لهذا التاريخ",
    "shiftFollowUp.open": "مفتوحة",
    "shiftFollowUp.closed": "مغلقة",
    "shiftFollowUp.notStarted": "لم تبدأ",
    "shiftFollowUp.editSuccess": "تم تحديث تعيين الوردية بنجاح",
    "shiftFollowUp.editError": "فشل تحديث تعيين الوردية",
    "shiftDashboard.title": "لوحة الورديات",
    "shiftDashboard.loading": "جاري التحميل...",
    "shiftDashboard.totalShifts": "إجمالي الورديات",
    "shiftDashboard.activeShifts": "نشطة",
    "shiftDashboard.totalAssignments": "إجمالي التعيينات",
    "shiftDashboard.openSessions": "الجلسات المفتوحة",
    "shiftDashboard.closedSessions": "الجلسات المغلقة",
    "shiftDashboard.pendingSessions": "الجلسات المعلقة",
    "shiftDashboard.recentAssignments": "التعيينات الحديثة",
    "shiftDashboard.noAssignments": "لا توجد تعيينات",
    
    // Shift Setup Page
    "shiftSetup.title": "إعداد الورديات",
    "shiftSetup.addTitle": "إضافة وردية جديدة",
    "shiftSetup.editTitle": "تعديل الوردية",
    "shiftSetup.shiftName": "اسم الوردية",
    "shiftSetup.shiftNamePlaceholder": "أدخل اسم الوردية",
    "shiftSetup.shiftZone": "منطقة الوردية",
    "shiftSetup.selectShiftZone": "اختر منطقة الوردية...",
    "shiftSetup.searchOrAddNew": "ابحث أو اكتب منطقة جديدة...",
    "shiftSetup.addNewZone": "إضافة",
    "shiftSetup.shiftType": "نوع الوردية",
    "shiftSetup.selectShiftType": "اختر نوع الوردية...",
    "shiftSetup.sales": "مبيعات",
    "shiftSetup.support": "دعم",
    "shiftSetup.startTime": "وقت البداية",
    "shiftSetup.endTime": "وقت النهاية",
    "shiftSetup.color": "لون الوردية",
    "shiftSetup.jobPositions": "المناصب الوظيفية",
    "shiftSetup.shiftAdmins": "مشرفي الوردية",
    "shiftSetup.addShift": "إضافة وردية",
    "shiftSetup.updateShift": "تحديث الوردية",
    "shiftSetup.saving": "جاري الحفظ...",
    "shiftSetup.cancel": "إلغاء",
    "shiftSetup.shiftsList": "قائمة الورديات",
    "shiftSetup.zone": "المنطقة",
    "shiftSetup.type": "النوع",
    "shiftSetup.actions": "الإجراءات",
    "shiftSetup.noPositionsAssigned": "لا يوجد مناصب مسندة",
    "shiftSetup.noAdminsAssigned": "لا يوجد مشرفين",
    "shiftSetup.noShiftsFound": "لم يتم العثور على ورديات. أضف أول وردية أعلاه.",
    "shiftSetup.deleteConfirm": "هل أنت متأكد من حذف هذه الوردية؟",
    "shiftSetup.zoneAddedSuccess": "تمت إضافة منطقة الوردية بنجاح",
    "shiftSetup.addedSuccess": "تمت إضافة الوردية بنجاح",
    "shiftSetup.updatedSuccess": "تم تحديث الوردية بنجاح",
    "shiftSetup.deletedSuccess": "تم حذف الوردية بنجاح",
    "shiftSetup.fillAllFields": "يرجى ملء جميع الحقول المطلوبة",
    "shiftSetup.errorFetchShifts": "فشل في جلب الورديات",
    "shiftSetup.errorFetchZones": "فشل في جلب مناطق الورديات",
    "shiftSetup.errorFetchPositions": "فشل في جلب المناصب الوظيفية",
    "shiftSetup.errorFetchUsers": "فشل في جلب المستخدمين",
    "shiftSetup.errorAddZone": "فشل في إضافة منطقة الوردية",
    "shiftSetup.errorSaveShift": "فشل في حفظ الوردية",
    "shiftSetup.errorDeleteShift": "فشل في حذف الوردية",
    "shiftSetup.noZonesFound": "لم يتم العثور على مناطق ورديات.",
    
    // Common
    "common.success": "نجح",
    "common.error": "خطأ",
    "common.loading": "جاري التحميل...",
    "common.all": "الكل",
    "common.confirm": "تأكيد",
    "common.cancel": "إلغاء",
    "common.back": "رجوع",
    "common.clearFilters": "مسح الفلاتر",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ar");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language || "ar";
    setLanguage(savedLanguage);
    document.documentElement.setAttribute("lang", savedLanguage);
    document.documentElement.setAttribute("dir", savedLanguage === "ar" ? "rtl" : "ltr");
  }, []);

  const toggleLanguage = () => {
    const newLanguage: Language = language === "en" ? "ar" : "en";
    setLanguage(newLanguage);
    localStorage.setItem("language", newLanguage);
    document.documentElement.setAttribute("lang", newLanguage);
    document.documentElement.setAttribute("dir", newLanguage === "ar" ? "rtl" : "ltr");
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.en] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}