
ALTER TABLE public.timesheets 
ADD COLUMN IF NOT EXISTS changed_start TEXT,
ADD COLUMN IF NOT EXISTS changed_end TEXT,
ADD COLUMN IF NOT EXISTS changed_by TEXT,
ADD COLUMN IF NOT EXISTS changed_at TIMESTAMPTZ;
