
ALTER TABLE public.tickets 
ADD COLUMN IF NOT EXISTS returned_for_clarification BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS returned_by TEXT DEFAULT NULL,
ADD COLUMN IF NOT EXISTS returned_at TIMESTAMPTZ DEFAULT NULL,
ADD COLUMN IF NOT EXISTS returned_comment TEXT DEFAULT NULL;
