CREATE TABLE public.products_backup (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  original_product_id UUID NOT NULL,
  backup_id TEXT NOT NULL,
  backed_up_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  backed_up_by TEXT,
  product_id TEXT,
  product_name TEXT NOT NULL,
  product_price TEXT,
  product_cost TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  brand_name TEXT,
  odoo_product_id INTEGER,
  odoo_sync_status TEXT DEFAULT 'not_synced',
  odoo_synced_at TIMESTAMP WITH TIME ZONE,
  sku TEXT,
  description TEXT,
  category TEXT,
  stock_quantity NUMERIC DEFAULT 0,
  minimum_order_quantity NUMERIC DEFAULT 1,
  reorder_point NUMERIC DEFAULT 0,
  weight NUMERIC,
  barcode TEXT,
  supplier TEXT,
  notes TEXT,
  mobile_enabled BOOLEAN DEFAULT true,
  coins_number NUMERIC DEFAULT 0,
  min_coins NUMERIC DEFAULT 0,
  max_coins NUMERIC DEFAULT 0,
  maximum_order_quantity NUMERIC DEFAULT 10,
  tax_type TEXT DEFAULT 'tax_included',
  free_coins JSONB DEFAULT '[]',
  options JSONB DEFAULT '[]',
  customer_group_prices JSONB DEFAULT '[]',
  discounts JSONB DEFAULT '[]',
  meta_title_ar TEXT,
  meta_keywords_ar TEXT,
  meta_description_ar TEXT,
  meta_title_en TEXT,
  meta_keywords_en TEXT,
  meta_description_en TEXT,
  leadtime NUMERIC DEFAULT 0,
  safety_stock NUMERIC DEFAULT 0,
  abc_analysis TEXT DEFAULT 'C',
  brand_code TEXT,
  brand_type TEXT,
  non_stock BOOLEAN NOT NULL DEFAULT false,
  allow_purchase BOOLEAN NOT NULL DEFAULT true,
  is_main_product BOOLEAN DEFAULT false,
  original_created_at TIMESTAMP WITH TIME ZONE,
  original_updated_at TIMESTAMP WITH TIME ZONE
);

ALTER TABLE public.products_backup ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Authenticated users can view backups" ON public.products_backup FOR SELECT TO authenticated USING (true);
CREATE POLICY "Authenticated users can insert backups" ON public.products_backup FOR INSERT TO authenticated WITH CHECK (true);